### ISSUE TITLE
[FEATURE]: Add support for short audio files in audio search data import

### ISSUE THREAD

**Issue by aharonh** [milvus-io/bootcamp#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Short audio files cause error in panns inference AudioTagging (in server/encode.py) and are being skipped while not being added to milvus index. 

### Describe the solution you'd like

I'd like to have the indexing detect short files and pad them with silence at the end so that the sound will be at least 1 second long and it will be indexed.

**Comment by shiyu22** [comment]
Hi @aharonh,

Thanks for your perfect PRs, and welcome to become the contributor 👍 

BTW, we are developing a project called Towhee [Towhee](https://github.com/towhee-io/towhee). It also has some pipelines about audio embedding, you can refer to [clmr](https://towhee.io/towhee/audio-embedding-clmr) and [vggish](https://towhee.io/towhee/audio-embedding-vggish).

Towhee will develop more and more embedded pipelines, so if you have any needs, please [feel free to contact us](https://github.com/towhee-io/towhee/issues).

**Comment by aharonh** [comment]
Hi @shiyu22 ,

Thanks for the kind words and the quick merge.

Will have a look into Towhee and the audio embedding examples for it, thanks for pointing to them.
