### ISSUE TITLE
[BUG]: Recall all 0 for 100 million benchmark test

### ISSUE THREAD

**Issue by xieliujie666** [milvus-io/bootcamp#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

milvus与python sdk版本均为1.1，在100万数据量下可以获得正确的recall结果，但是在一亿下的结果为0，已经将is_uint8配置为TRUE。

### Expected Behavior

获得正确的结果

### Steps To Reproduce

```markdown
跑script
```

### Software version

```markdown
Milvus:1.1
Server:1.1
Client:1.1
```

**Comment by JackLCL** [comment]
@xieliujie666
Which document are you following? Can you post a link?

**Comment by ss892714028** [comment]
@xieliujie666 Please use English in this repo for everyone's convenience, thanks!

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
