### ISSUE TITLE
[FEATURE]: reverse_image_search update towhee to 0.4.0

### ISSUE THREAD

**Issue by Folgerjun** [milvus-io/bootcamp#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

in reverse_image_search project, when i update towhee to 0.4.0 then many exceptions occurred.
Hoping for a new version based on towhee==0.4.0.

**Comment by shiyu22** [comment]
Same as #1045
