### ISSUE TITLE
[BUG]: Got a 2048 dimensions array when using encode_tf_resnet50 to extract image feature.

### ISSUE THREAD

**Issue by andy263** [milvus-io/bootcamp#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

How can I reduce it, like 1000, to woking with milvus？

### Expected Behavior

na

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
I think it depends on your model. You can change the dimension in predict.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
