### ISSUE TITLE
[BUG]: browser returns: {"detail":"Not Found"} in similar images research demo

### ISSUE THREAD

**Issue by tcexeexe** [milvus-io/bootcamp#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to launch a similar image search demo, l start the docker mysql by order 
`sudo docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.7`
then l start the docker milvus by order
`sudo docker-compose up -d`
all the docker status are as follows:
![image](https://user-images.githubusercontent.com/28287196/157205064-8e82fbd6-df44-4f23-ac1e-887949ba2dd6.png)
then l try to start the demo by input and access` localhost:5000`,the browser returns {"detail":"Not Found"}
`python src/main.py`

![image](https://user-images.githubusercontent.com/28287196/157204385-ff102d1b-9020-4b9d-9704-19ddc965aa75.png)
![image](https://user-images.githubusercontent.com/28287196/157204548-ce63636d-a879-48ac-aac4-e1c70379d6cb.png)

I wonder if anyone could tell me how to solve this problem

### Expected Behavior

start and use the similar images research demo

### Steps To Reproduce

```markdown
**********************************
```

### Software version

```markdown
Milvus: v2.0.1 
Server: ubuntu20.04
code: version master
```

### Anything else?

***********************************************

**Comment by elven2016** [comment]
the same too，have you solved this issue？
