### ISSUE TITLE
[BUG]: Import Chinese data set garbled

### ISSUE THREAD

**Issue by gouzil** [milvus-io/bootcamp#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![截屏2022-03-24 下午5 22 09](https://user-images.githubusercontent.com/66515297/159884585-3fb4a012-db25-467f-8644-1180e9851f27.png)
![101741648114091_ pic](https://user-images.githubusercontent.com/66515297/159885566-617abe1b-2768-46a7-9019-627526a959bd.jpg)

### Expected Behavior

![截屏2022-03-24 下午5 22 27](https://user-images.githubusercontent.com/66515297/159884489-d34e07a0-d083-40f9-aeb6-95595cebc71b.png)

### Steps To Reproduce

```markdown
Docker
1.FastAPI
2.post /qa/load_data
3.file
4.Internal Server Error
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc3]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
@gouzil  I think you fixed it by yourself👍, can you close it?
