### ISSUE TITLE
[BUG]: search by question tuple index out of range

### ISSUE THREAD

**Issue by gouzil** [milvus-io/bootcamp#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Get /qa/answer

![截屏2022-03-25 上午10 29 41](https://user-images.githubusercontent.com/66515297/160043239-7d922db1-abc3-4844-abfc-f7d2faacc1cf.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/66515297/160043974-6873a852-89ed-416b-ba94-2711c8c34a1f.png)

### Steps To Reproduce

```markdown
Docker
1. open FastAPI 
2. Get /qa/answer
3. enter question and table_name

4. err: 
22-03-25 01:57:23,854 ｜ ERROR ｜ mysql_helpers.py ｜ search_by_question ｜ 80 ｜ MYSQL ERROR: tuple index out of range with sql: select answer from test1 where question = '*********';
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/src/mysql_helpers.py", line 78, in search_by_question
    return results[0][0]
IndexError: tuple index out of range
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc3]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
@gouzil  I think you fixed it by yourself👍, can you close it?
