### ISSUE TITLE
Copy the data from one computer to another

### ISSUE THREAD

**Issue by it950** [milvus-io/bootcamp#1043]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

We have 500G images in our disk, and want to deploy [reverse image search](https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy) on our local computer to help our sales to quickly find an image, 
there are some questions about **reverse image search**  and would like to hear your advise:
1. Does the  data in docker can be copied from one computer to another, eg: replace the old computer with a new computer.
2. There are some way to improve the performance.
3. Each time when type */data* data path the demo training all images, can we only train the new added images? 

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by JackLCL** [comment]
1. Yes. When docker starts, you can use the -v parameter for data mapping, so you only need to copy the directory you mapped to other machines, then you can start on other machines.
2. The whole performance of image search is divided into two parts, one is the time for image feature extraction, and the other is the time for milvus to do vector retrieval. If you find that image feature extraction takes a long time, you can try to use gpu to speed up. If you find that milvus takes a long time to search, you can adjust the parameters of milvus by referring to the official website.（https://milvus.io/docs/v2.0.x/performance_faq.md）
3. Yes. You can create a subdirectory inside you mapping directory. Then you put your new pictures in the subdirectory.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
