### ISSUE TITLE
[BUG]: Hope to update to the latest version towhee 

### ISSUE THREAD

**Issue by emmataobao** [milvus-io/bootcamp#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
We will update it when towhee 0.6.0 release :) maybe this month.

**Comment by shiyu22** [comment]
Updated in #1046
