### ISSUE TITLE
在使用视频搜索系统时server容器总是报错  INFO:     172.16.238.1:48462 - "POST /video/load HTTP/1.1" 500 Internal Server Error  [BUG]: 

### ISSUE THREAD

**Issue by yuhan171** [milvus-io/bootcamp#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在使用视频搜索系统加载图片时，查看服务器总是报错INFO:     172.16.238.1:48462 - "POST /video/load HTTP/1.1" 500 Internal Server Error

### Software version

```markdown
Milvus: [e.g. 2.0.2]
```

**Comment by ss892714028** [comment]
Please use English in this repo as we have users around the globe.
Would you please give a bit more information? Is the Milvus server healthy? It would be very helpful if you could post some Milvus log here.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
