### ISSUE TITLE
[BUG]: Mention of Postgres in the Question Answering Bootcamp Example Should be MySql

### ISSUE THREAD

**Issue by myntoralex** [milvus-io/bootcamp#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
I think the latest [QA system](https://github.com/milvus-io/bootcamp/tree/master/solutions/question_answering_system/quick_deploy) is used MySql instead of Postgres. Did you try it?

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
