### ISSUE TITLE
when "docker-compose up -d", got error: "networks.app_net.ipam.config value Additional properties are not allowed ('gateway' was unexpected)"

### ISSUE THREAD

**Issue by yangmh66** [milvus-io/bootcamp#1053]
when tried to compose docker,
          $ docker-compose up -d
 got an error like this:
          ERROR: The Compose file './docker-compose.yaml' is invalid because:
          networks.app_net.ipam.config value Additional properties are not allowed ('gateway' was unexpected)

![image](https://user-images.githubusercontent.com/17701158/168220661-05ab8c14-389f-4a2e-91e9-418f026550b9.png)

My docker version:
$ docker --version
Docker version 20.10.16, build aa7e414
$ docker-compose --version
docker-compose version 1.25.0, build unknown

Any suggestion?

**Comment by shiyu22** [comment]
Can you update the docker-compose and try again?

**Comment by yangmh66** [comment]
It works after update the docker-compose version to v2.5.0
Thanks for your helps!
