### ISSUE TITLE
[BUG]: 5000 port is inused

### ISSUE THREAD

**Issue by superior-god** [milvus-io/bootcamp#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当运行https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy的docker-compose up -d，会出现有个5000端口号，系统禁止是使用

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
@superior-god I think you need to check the 5000 port is already in use with `sudo netstat -an | grep 8000`.

**Comment by selected-pixel-jameson** [comment]
If you are running MacOS going to Settings -> Sharing -> Disable Airplay Receiver.
