### ISSUE TITLE
[FEATURE]: Is there a solution about imae duplication?

### ISSUE THREAD

**Issue by GongZhengLi** [milvus-io/bootcamp#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

我想对亿级的图片数据进行去重

### Describe the solution you'd like

能否之间基于milvus实现 ？

**Comment by shiyu22** [comment]
I think you can try Towhee, and there is an Example about [image depulication](https://github.com/towhee-io/examples/blob/main/image/image_deduplication/image_deduplication.ipynb).

And you can resolve the large-scale data with Milvus. You can refer to [reverse-image-search](https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy#option-2-deploy-with-source-code) solution, and you can set the threshold of search results to filter out duplicate images like in towhee-example.
