### ISSUE TITLE
[BUG]: ERROR: Could not find a version that satisfies the requirement pandas==1.1.5; python_version < "3.7"

### ISSUE THREAD

**Issue by Scarlett-xu** [milvus-io/bootcamp#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在安装pymilvus-2.0.2时，使用python3 -m pip install pymilvus==2.0.2，
出现：ERROR: Could not find a version that satisfies the requirement pandas==1.1.5; python_version < "3.7" (from pymilvus) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3)
ERROR: No matching distribution found for pandas==1.1.5; python_version < "3.7"
环境是python3.6

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
I think Milvus required Python 3.71 or later, more information you can refer to the website: https://milvus.io/docs/v2.0.x/example_code.md#Preparations.
