### ISSUE TITLE
[BUG]: 'gateway' was unexpected

### ISSUE THREAD

**Issue by JinXia77** [milvus-io/bootcamp#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the docker-compose followed by /bootcamp/solution/reverse_image_search/quick_deploy readme. The error occured shown below.
ERROR: The Compose file './docker-compose.yaml' is invalid because:
networks.app_net.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
![error_shotcut](https://user-images.githubusercontent.com/110447054/183581778-f753fcd8-025e-41d6-83dd-c70cbdd1ea44.png)

### Steps To Reproduce

```markdown
1. I am running the solution of https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy

2. $ git clone https://github.com/milvus-io/bootcamp.git
$ cd solutions/reverse_image_search/quick_deploy
$ vim docker-compose.yaml

3. $ docker-compose up -d
occur an error
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
@JinXia77 which version of docker-compose are you using? I think milvus is required Docker(19.03 or later) and Docker Compose(1.25.1 or later), you can check it with `docker --version` and `docker-compose --version`.

**Comment by JinXia77** [comment]
> @JinXia77 which version of docker-compose are you using? I think milvus is required Docker(19.03 or later) and Docker Compose(1.25.1 or later), you can check it with `docker --version` and `docker-compose --version`.

I used docker 20.10.17 and docker-compose 1.25.1 and error occured. Now I had update my docker-compose to 1.29.2 and it works! Thank you very much!

**Comment by JinXia77** [comment]
> @JinXia77 which version of docker-compose are you using? I think milvus is required Docker(19.03 or later) and Docker Compose(1.25.1 or later), you can check it with `docker --version` and `docker-compose --version`.

Another error occured, for now, I have finished docker-compose and changed the data_path to my own data path. For checking the images have been sent to the docker container, I also went into the img-search-webserver containter and the data folder and its images are all exist shown below . 
![no_response](https://user-images.githubusercontent.com/110447054/183625678-b6ee72aa-d86e-4afa-b4c1-b042b441388e.png)

But when I use "+" button to load images, there is no response and it shows that "no image in this set".  Actually I do not understand why the web told me that there is no image in this set
![web](https://user-images.githubusercontent.com/110447054/183625696-f72b0973-2215-415e-a9cb-ec25aae9221d.png)

Besides, I also check the log info of milvus-standalone which shows below. So do you know how to solve the problem?
![logs_standlone](https://user-images.githubusercontent.com/110447054/183625704-8278e06d-6786-44e5-a6dd-b1790896c065.png)

**Comment by shiyu22** [comment]
Can you run `docker logs img-search-webserver` to get the log of webserver? And is there any error message?

**Comment by shiyu22** [comment]
Please check you have successfully start all the docker images, and you can run `docker-compose ps` under **solutions/reverse_image_search/quick_deploy** to get the status of all container.

**Comment by JinXia77** [comment]
> Please check you have successfully start all the docker images, and you can run `docker-compose ps` under **solutions/reverse_image_search/quick_deploy** to get the status of all container.
> 
> And one question, are you modifying the docker-compose.yaml?

The docker status seems normal shown below. And the only one thing I changed is the data path at 73 line in docker-compose.yaml from data path to my own data path.

![compose_status](https://user-images.githubusercontent.com/110447054/183630926-20a4b92d-0388-4e41-b8e0-1cba06e0e9a5.png)

![data](https://user-images.githubusercontent.com/110447054/183630925-3c69cf45-fc18-4733-a448-16fcdcf6462e.png)

**Comment by shiyu22** [comment]
@JinXia77 The status of the container seems normal. In the log you posted earlier, it was found that Milvus was successfully connected at the end. Can you try to rerun load and follow-up message docker logs? It may be that Milvus has not been started yet in your previous operation.

BTW, you can check the network information on the web with developer mode(F12).
<img width="614" alt="截屏2022-08-09 19 11 17" src="https://user-images.githubusercontent.com/53459423/183633878-b915b802-8f95-41fd-891b-b683dd093523.png">

**Comment by JinXia77** [comment]
> @JinXia77 The status of the container seems normal. In the log you posted earlier, it was found that Milvus was successfully connected at the end. Can you try to rerun load and follow-up message docker logs? It may be that Milvus has not been started yet in your previous operation.
> 
> BTW, you can check the network information on the web with developer mode(F12). <img alt="截屏2022-08-09 19 11 17" width="614" src="https://user-images.githubusercontent.com/53459423/183633878-b915b802-8f95-41fd-891b-b683dd093523.png">


I rerun the load, there are only two docker containers output logs which are milvus_standalone and img-search-webclient. The logs shown below.
milvus_standalone logs: 
![standalone_load_logs](https://user-images.githubusercontent.com/110447054/183793785-14f0f142-badc-489c-b838-d1f8d7629a98.png)

img-search-webclient logs:
![img_search_webclient_load_logs](https://user-images.githubusercontent.com/110447054/183794249-5f1b63f8-1e2e-42f3-a8c9-3bc0d0453520.png)


On the other hand, I also check the network information on the web which is show below:
![network](https://user-images.githubusercontent.com/110447054/183794329-157d61ad-031c-4913-8ce5-b22cd8b22d01.png)

**Comment by shiyu22** [comment]
You can click load and check the Response. Seems like the webserver has not received the request if there no log in webserver.

**Comment by JinXia77** [comment]
> You can click load and check the Response. Seems like the webserver has not received the request if there no log in webserver.

Yes, there is no response from load. It shows no data found. What might be the reason for this problem?
![web_noresponse](https://user-images.githubusercontent.com/110447054/183800037-42ce944b-fe1c-471b-8e64-4dd4cc7e0704.png)

**Comment by JinXia77** [comment]
> You can click load and check the Response. Seems like the webserver has not received the request if there no log in webserver.

Hi, for now I can access th websever according to change the environment from API_URL:'http://127.0.0.1:5000' to my gpu sever ip address(although, I set these docker services at my gpu sever). Then, I watched the log info in img-search-webserver, it shows that it is downloading  opencv_python. However, the download speed is too slow, so I want to ask where the opencv_python(maybe there are other dependencies?) will be downloaded so that I can download the opencv file with other source and move the file to where it should be. The logs of websever is shown below.
![web_sever](https://user-images.githubusercontent.com/110447054/183810095-8ea6f00a-4437-4e87-bacf-728e0df1f128.png)

**Comment by shiyu22** [comment]
Yes, you can run with another pypi source in the webserver container, for example:
```bash
# 1. enter the webserver container
$ docker exec -ti img-search-webserver bash
# 2. install opencv-python with another source:
$ pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by JinXia77** [comment]
> 
These problems will drive me crazy.... Another problem is that when i load these images, the web_sever container logs that "Error with extracting feature from image unexpected EOF" shown below
![extract_features_error](https://user-images.githubusercontent.com/110447054/183835356-aaf3e411-51d2-4a9f-9348-803b98f48087.png)
And hence, there is no entities loaded in collections, the attu show the infomation of current collenctions
![attu](https://user-images.githubusercontent.com/110447054/183837802-7f506301-5032-4199-a8bd-6f55e867a12c.png)


I also check the function of load.py and the "model" shown in load.py, the model will load a resnet50 model and do the pipeline. Run the same code in the gpu server, it can run normally shown below. However, in the docker container, the load() will raise an error shown in the first figure above.

![gpu_normal](https://user-images.githubusercontent.com/110447054/183837392-71930e23-fa63-479a-8c76-57c2d3b7ec12.png)

**Comment by JinXia77** [comment]
> Yes, you can run with another pypi source in the webserver container, for example:
> 
> ```shell
> # 1. enter the webserver container
> $ docker exec -ti img-search-webserver bash
> # 2. install opencv-python with another source:
> $ pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple
> ```

Also, for check whether the figures are good or corrupted in /data in image_search_sever container. I also copy the figure from docker in to gpu sever. The result is the figure copied from docker can be viewed normally in gpu sever.
![from_docker](https://user-images.githubusercontent.com/110447054/183839227-1f15f615-caa8-45de-a47a-53a1f52f63b5.png)

**Comment by shiyu22** [comment]
> Also, for check whether the figures are good or corrupted in /data in image_search_sever container. I also copy the figure from docker in to gpu sever. The result is the figure copied from docker can be viewed normally in gpu sever.

The EOF error is because of resnet50 model download error, and you can refer to [it](https://blog.csdn.net/qq_39691492/article/details/123073208). So you can remove the (.pth) in docker and rerun, also you can download it in your local env and cp it to container with `docker cp `.

**Comment by JinXia77** [comment]
> > Also, for check whether the figures are good or corrupted in /data in image_search_sever container. I also copy the figure from docker in to gpu sever. The result is the figure copied from docker can be viewed normally in gpu sever.
> 
> The EOF error is because of resnet50 model download error, and you can refer to [it](https://blog.csdn.net/qq_39691492/article/details/123073208). So you can remove the (.pth) in docker and rerun, also you can download it in your local env and cp it to container with `docker cp `.

Yes! You are right, I download the pretrained model and cp it to the image_search_sever container. For now, it work! Thank you very much! The successful result is shown below.
![finish](https://user-images.githubusercontent.com/110447054/183851380-0fd3c589-3338-4270-9ec6-62888938bbf1.png)

Here I have some suggestions, these are all the problems I encountered when I try to realize the functions of web image search. The image_search_sever container still lack of some dependencies, such like torch, timm, python_opencv. You can also add these dependencies into requirements.txt below the sever folder.

Anyway, Thank you very much for solving my so many problems!

**Comment by shiyu22** [comment]
Very happy finally it works :)

The python package you mentioned is actually a package that will be automatically installed in the [Tohwee Operator](https://towhee.io/image-embedding/timm). It has corresponding requirements.txt in the operator but not in this solution. Actually, we are also collecting the Q&A about Bootcap, I think your question is good and we will record it for other users.
