### ISSUE TITLE
[Question] what happened if i only do create_index() on collection creation not everytime i insert to collection?

### ISSUE THREAD

**Issue by utopictown** [milvus-io/bootcamp#1065]
was wondering because usually in SQL we only create index once for table but in example quick deploy we create index everytime we insert data to collection

**Comment by shiyu22** [comment]
Actually, you can call `create_index()` only once and Milvus will automatically build an index when the data size reaches the sealed segment size, which is determined by [datacoord.segment.maxSize](https://milvus.io/docs/v2.1.x/configure_datacoord.md#dataCoordsegmentmaxSize) and [datacoord.segment.sealProportion](https://milvus.io/docs/v2.1.x/configure_datacoord.md#dataCoordsegmentsealProportion).

The difference is that if you manually call create_index after inserting data, Milvus will create an index for the remaining data. At this time, the amount of data does not need to reach the size of the sealed segment, but it is required to be higher than [rootCoord.minSegmentSizeToEnableIndex](https://milvus.io/docs/v2.1.x/configure_rootcoord.md#rootCoordminSegmentSizeToEnableIndex).

I think all the data inserted into the system needs to be indexed, so create_index will be called after each data insertion. Of course, you can also use create Index once after creating the Milvus collection.

**Comment by utopictown** [comment]
@shiyu22 thank you for the answer, i have problem in querying the vectors, it took too long and never succeed, does this has anyhting to do with the indexing?

**Comment by shiyu22** [comment]
I think this is related to your data scale and hardware. You can run `docker logs milvus-standalone` to view the logs. If there are any error messages, you can submit an [issue to the Milvus](https://github.com/milvus-io/milvus/issues) project.

BTW, you can first run Milvus on a small scale to check it.
