### ISSUE TITLE
以图搜图：找不到数据集

### ISSUE THREAD

**Issue by 1344265305** [milvus-io/bootcamp#1068]
请问使用docker-compose部署后，path/to/images怎么填写？
添加路径，点＋以后，docker提示：[Errno 2] No such file or directory: 'F:/milvus/VOCdevkit/VOC2007/JPEGImages'

docker是windows系统内搭建的

![屏幕截图 2022-09-02 174820](https://user-images.githubusercontent.com/102736689/188113351-cb21d594-be38-4aab-9e0d-f1992909656d.png)

**Comment by shiyu22** [comment]
Hi @1344265305, please check `webserver.volumes` in docker-compose.yaml to mout your images into container. BTW you can check it with  [Bootcamp FAQ](webserver.volumes in docker-compose.yaml).

**Comment by 1344265305** [comment]
> Hi @1344265305, please check `webserver.volumes` in docker-compose.yaml to mout your images into container. BTW you can check it with [Bootcamp FAQ](https://github.com/milvus-io/bootcamp/blob/master/bootcamp_faq.md).

十分感谢您的回复
