### ISSUE TITLE
[BUG]: /img/count is getting stuck

### ISSUE THREAD

**Issue by zhenzi0322** [milvus-io/bootcamp#1072]
I'm requesting the server interface/img/count from https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy and I'm getting stuck, what's the reason for this? What is the cause of this?

**Comment by shiyu22** [comment]
Is there any logs of webserver? Please check in [FAQs](https://github.com/milvus-io/bootcamp/blob/master/bootcamp_faq.md) if there no logs in weberver.

**Comment by zhenzi0322** [comment]
> Is there any logs of webserver? Please check in [FAQs](https://github.com/milvus-io/bootcamp/blob/master/bootcamp_faq.md) if there no logs in weberver.

Web service logs are available. But after requesting /img/load, I get stuck for a long time when I request /img/count again

**Comment by zhenzi0322** [comment]
> Is there any logs of webserver? Please check in [FAQs](https://github.com/milvus-io/bootcamp/blob/master/bootcamp_faq.md) if there no logs in weberver.

I've figured out the problem, it's the load method in which collection is loaded into memory that affects all requests.
