### ISSUE TITLE
[BUG]: Failed to load data to Milvus: Collection field dim is 512, but entities field dim is 2048

### ISSUE THREAD

**Issue by zhenzi0322** [milvus-io/bootcamp#1108]
https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy/server/src

Failed to load data to Milvus: Collection field dim is 512, but entities field dim is 2048

**Comment by Administor123** [comment]
Hi, I had the same problem, have you solved it yet?

**Comment by shiyu22** [comment]
Have you changed the encoding method? Can you try with the [latest code](https://github.com/milvus-io/bootcamp/tree/master/solutions/image/reverse_image_search) or modify [the dimension](https://github.com/milvus-io/bootcamp/blob/master/solutions/image/reverse_image_search/server/src/config.py#L6) yourself?

**Comment by Administor123** [comment]
> Have you changed the encoding method? Can you try with the [latest code](https://github.com/milvus-io/bootcamp/tree/master/solutions/image/reverse_image_search) or modify [the dimension](https://github.com/milvus-io/bootcamp/blob/master/solutions/image/reverse_image_search/server/src/config.py#L6) yourself?

Thanks for your reply, I managed to solve the problem yesterday after changing the dataset, maybe the dataset I was using before was not appropriate
