### ISSUE TITLE
[BUG]: Reverse Image Search quick deploy request failed due to CORS

### ISSUE THREAD

**Issue by soulteary** [milvus-io/bootcamp#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/1500781/192063403-40c0a34d-4995-46a0-9733-3bd501a09f06.png)

### Expected Behavior

can be used normally

### Steps To Reproduce

```markdown
1. git clone
2. cd solutions/reverse_image_search/quick_deploy/
3. docker-compose up / docker compose up
4. wait for docker container ready ( webclient will not be healthy, but that's nothing
5. access port 8001 and load images
```

### Software version

```markdown
master branch
```

**Comment by imSaharukh** [comment]
same issue

**Comment by sshen81** [comment]
If you're attempting to run the examples on Mac Monterey, port 5000 is consumed by the Control Center's Airplay Receiver service. Adjust the docker compose setup to utilize an available port and the bootcamp example should begin working.

https://developer.apple.com/forums/thread/682332

**Comment by imSaharukh** [comment]
> If you're attempting to run the examples on Mac Monterey, port 5000 is consumed by the Control Center's Airplay Receiver service. Adjust the docker compose setup to utilize an available port and the bootcamp example should begin working.
> 
> https://developer.apple.com/forums/thread/682332

sorry this is not the issue

**Comment by soulteary** [comment]
@imSaharukh  hi, i think this demo is better for you
https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/one_step

**Comment by fall-nebula** [comment]
same issue

**Comment by it-noob** [comment]
same issue, and the health check exception you mentioned for the webclient is because the webclient docker container does not have a curl command, but the compose uses
