### ISSUE TITLE
[BUG]: About the correct writing of the word MySQL in the document

### ISSUE THREAD

**Issue by KID-G** [milvus-io/bootcamp#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mysql 

### Expected Behavior

MySQL

> Except for the code parameter command part

### Steps To Reproduce

```markdown
no steps
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

### Anything else?

no

**Comment by shiyu22** [comment]
Hi @KID-G, can you submit PR to update it?
