### ISSUE TITLE
用发行版bootcamp-2.0.2，docker方式搭建好后，搜索视频没有缩略图，但复制html的链接后可以打开播放

### ISSUE THREAD

**Issue by wangzixuank** [milvus-io/bootcamp#1116]
![55b6d2d628b5975a11c6002ab4145c3](https://user-images.githubusercontent.com/21374501/198862665-1c348117-3bf7-4948-af1f-114efd5ea8ed.png)

docker logs video-webserver
![38eb811afb440a61ff34ee31b3892eb](https://user-images.githubusercontent.com/21374501/198862677-ba869e5e-3adc-4ece-a83d-83777453b4a7.png)

**Comment by nieshaokang** [comment]
![image](https://user-images.githubusercontent.com/21374501/198862730-54fa2e2b-7f91-4394-81c9-66067a745a21.png)

**Comment by shiyu22** [comment]
Hi @nieshaokang, I cannot reproduce it, it works on my machine :( So can you check your network or rerun it?
