### ISSUE TITLE
[BUG]: example Notebook link 404 error

### ISSUE THREAD

**Issue by gurkanctn** [milvus-io/bootcamp#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

under `bootcamp/solutions/image/reverse_image_search/` 
the example notebook link is broken.

### Expected Behavior

link should take the visitor to a functional page

### Steps To Reproduce

```markdown
1. Go to bootcamp/solutions/image/reverse_image_search/
2. click the Notebook link
```

### Software version

```markdown
N/A
```

**Comment by jaelgu** [comment]
Fixed.
