### ISSUE TITLE
[BUG]: Solving booting up failure due to towhee package pulling for reverse_image_search

### ISSUE THREAD

**Issue by hyyz17200** [milvus-io/bootcamp#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes, I have experienced this issue multiple times in months. The reverse_image_search bootcamp will report a failure when initializing the towhee module.

When I docker-compose up the bootcamp, it successfully booted. The webserver and webclient are all working.

However, if I search an image, the docker log shows that it is download files towhee.io
The downloading is okay. But finally, it gave me an error. The keypoint is:

`cannot import name 'get_pretrained_cfg' from 'timm.models' (/usr/local/lib/python3.7/site-packages/timm/models/__init__.py)`

Of course, the reverse-image-search won't work. No picture returned.

### Expected Behavior

It should give me many picture results, as we all know.

### Steps To Reproduce

```markdown
1. Boot up the reverse-image-search bootcamp by docker-compose
2. Search an image to let the bootcamp initial dependency packages
3. keep an eye on logs. The error will occur

Notice:
It will only reproduce the result at rare times. When the towhee code was just updated, or when towhee has network delivery issues?
```

### Software version

```markdown
Before I solve this, the versions are all from the bootcamp:

Milvus: milvusdb/milvus:v2.0.2
Server: milvusbootcamp/img-search-server:towhee0.6
Client: milvusbootcamp/img-search-client:1.0

And I am attaching the python packages version from current webserver's docker environment below:

pip3 list --outdated
Package            Version   Latest    Type
------------------ --------- --------- -----
aiofiles           0.7.0     22.1.0    wheel
certifi            2021.10.8 2022.12.7 wheel
charset-normalizer 2.0.12    3.0.1     wheel
click              7.1.2     8.1.3     wheel
diskcache          5.2.1     5.4.0     wheel
fastapi            0.65.2    0.89.1    wheel
grpcio             1.37.1    1.51.1    wheel
grpcio-tools       1.37.1    1.51.1    wheel
h11                0.13.0    0.14.0    wheel
idna               3.3       3.4       wheel
numpy              1.21.3    1.21.6    wheel
opencv-python      4.5.5.64  4.7.0.68  wheel
Pillow             8.4.0     9.4.0     wheel
protobuf           3.20.0    4.21.12   wheel
pydantic           1.8.2     1.10.4    wheel
pymilvus           2.0.2     2.2.1     wheel
pytz               2022.1    2022.7.1  wheel
requests           2.27.1    2.28.2    wheel
ruamel.yaml        0.16.6    0.17.21   wheel
ruamel.yaml.clib   0.2.6     0.2.7     wheel
setuptools         57.5.0    67.1.0    wheel
starlette          0.14.2    0.23.1    wheel
tabulate           0.8.9     0.9.0     wheel
timm               0.5.4     0.6.12    wheel
torch              1.11.0    1.13.1    wheel
torchvision        0.12.0    0.14.1    wheel
towhee             0.6.0     0.9.0     wheel
tqdm               4.64.0    4.64.1    wheel
typing_extensions  4.1.1     4.4.0     wheel
ujson              5.1.0     5.7.0     wheel
urllib3            1.26.9    1.26.14   wheel
uvicorn            0.13.4    0.20.0    wheel
wheel              0.37.1    0.38.4    wheel
```

### Anything else?

This issue may have a relation with this one:
https://github.com/towhee-io/towhee/issues/1201 

I have a unique solution today, which I will attach in reply.

**Comment by hyyz17200** [comment]
There's a behavior that the bootcamp's docker won't keep any python or towhee packages on volumes locally. That's why every time we boot up the bootcamp, it downloads massive data before it gives us the search result.  

Besides the waste of time and network usage, it may also result in the possibility that if any upstream updating bug or network error. The bootcamp won't start.

The towhee package is always pulled with the newest version from towhee.io, while the Milvus and other components are not.

I updated all the related python packages to see if the newer ones work well with the latest towhee.

I typed these:

```
exec -it img-search-webserver  bash 
pip3 list --outdated
pip3 install --upgrade pymilvus timm torch torchvision towhee
rm -rf /root/.towhee           
```
 
And after this, the bootcamp is working. 

This may not be a good solution. But to me, it works like a charm.

**Comment by hyyz17200** [comment]
Also, I used a way to keep packages saved locally to avoid massive network loading when booting up. 
I think this should also reduce failure possibility.

Edit this file:
`reverse_image_search/quick_deploy/docker-compose.yaml`

Add below into services:/etcd:/volumes:
`      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
`
Add below into services:/minio:/volumes:
`      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
`
Add below into services:/standalone:/volumes:
`      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
`
Add below into services:/mysql:/volumes:
`      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mysql:/var/lib/mysql
`
Add below into services:/webserver:/volumes:
```
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/webserver/site-packages:/usr/local/lib/python3.7/site-packages
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/webserver/.towhee:/root/.towhee/
```


The final yaml file I edited, is this:

[docker-compose.zip](https://github.com/milvus-io/bootcamp/files/10567339/docker-compose.zip)

**Comment by shiyu22** [comment]
The code about reverse image search is updated.
