### ISSUE TITLE
[BUG]: 官网中文本搜索后端代码的检索问题

### ISSUE THREAD

**Issue by lijinmei519** [milvus-io/bootcamp#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, when doing a text semantic search, the link is as follows: https://github.com/milvus-io/bootcamp/tree/master/solutions/nlp/text_search_engine/quick_deploy/server.
When the backend is just started, the search can come out in about two or three seconds, which is a relatively normal search state. But after a little time, it takes a long time to perform the same search again, and the backend is stuck in the /search interface, so I have to restart the backend again.
I look forward to your reply, thank you!

### Expected Behavior

As long as the back-end start, you can achieve stable and fast search, there will be no search for a long time out of the situation.

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
Are there any logs? It you are using the docker method, you can run `docker logs text-search-webserver` to show the logs.
