### ISSUE TITLE
[BUG]: img-search-webclient 上传图片无响应

### ISSUE THREAD

**Issue by huan415** [milvus-io/bootcamp#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 云服务器上下载 bootcamp-2.0.2
2. 修改docker-compose.yaml 中 的webclient.environment.API_URL为服务器地址
3. docker-compose -up -d 启动
4. docker logs看日志正常，无报错
5. copy 图片文件夹到img-search-webserver docker中
6. client 页面上上传图片
6上传图片有请求，无响应（无报错日志）

![微信图片_20230605202419](https://github.com/milvus-io/bootcamp/assets/37132274/2c87a5cf-129a-4554-afd5-ab7e58dd9eaa)

![微信图片_20230605202425](https://github.com/milvus-io/bootcamp/assets/37132274/455fff07-d5cb-498e-9f3c-8f70425173e8)

### Software version

```markdown
Milvus: milvus:v2.0.2
Server: img-search-server:towhee0.6
Client: img-search-client:1.0
```

**Comment by huan415** [comment]
刷新页面都是No image in this set，
且xxx: 5000/img/count 请求状态都是 pending，查不出数据

**Comment by shiyu22** [comment]
Hi @huan415, can you try with the latest code?

**Comment by qrpengx** [comment]
@huan415 你可以试试修改docker-compose.yaml文件webclient处 API_URL: 'http://127.0.0.1:5000' 把 127.0.0.1 改成docker主机的ip地址

**Comment by yaochao1** [comment]
这个问题最后解决了吗？我现在也遇到了

**Comment by 051611** [comment]
我也是同样的问题

**Comment by DAAworld** [comment]
你要看一下这里面有没有图片。是否是支持的图片格式。

**Comment by listento123** [comment]
我也遇到了，并不是图片的格式问题，我只加载一张图片，都无法加载

**Comment by codingjaguar** [comment]
Thanks for reporting the issue. We have developed a new version of image search example in https://github.com/milvus-io/bootcamp/blob/master/bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb, utilizing the latest available open-source models and the just released easy-to-install Milvus Lite (https://github.com/milvus-io/milvus-lite).
