### ISSUE TITLE
[FEATURE]: text_search_engine/quick_deploy /docker-compose.yaml

### ISSUE THREAD

**Issue by Fakeraway** [milvus-io/bootcamp#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When installing this demo, it is not clear where the files need to be modified.

### Describe the solution you'd like

In this yaml file, I need to prepare at least a few server IPs for replacement, and what places need to be modified, can you describe in detail?

### Describe alternatives you've considered

The place that needs to be replaced is noted in the file

**Comment by shiyu22** [comment]
This file is removed.
