### ISSUE TITLE
这个仓库历史上已经有了3版本图搜图的代码，哪个版本的效果会好点，区别是什么？

### ISSUE THREAD

**Issue by DAAworld** [milvus-io/bootcamp#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://github.com/milvus-io/bootcamp/tree/master/applications/image/reverse_image_search
^
这个是最新的搜图。
https://github.com/milvus-io/bootcamp/tree/1.0/solutions/image_search2
^
这个是第二版用的是ResNet50模型。
还有一版用的是VGG16模型。这三个用的图像embedding的区别是什么呢？

**Comment by junjiejiangjjj** [comment]
The data used by others to train the model may be different from your data, so you need to test it with real data to determine the effect. If the effect isn't good enough, you should consider using your data for training.

**Comment by codingjaguar** [comment]
The image embedding is a scattered and fast evolving space. Some of the latest popular models includes CLIP and ViT but not limited to them. And this can change very fast so we couldn't give always up-to-date suggestion. You can check the model description and feedback in communities such as HuggingFace.

**Comment by listento123** [comment]
May I ask if the code link for the first version using VGG cannot be found? Is there still a link available

**Comment by listento123** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> https://github.com/milvus-io/bootcamp/tree/master/applications/image/reverse_image_search ^ 这个是最新的搜图。 https://github.com/milvus-io/bootcamp/tree/1.0/solutions/image_search2 ^ 这个是第二版用的是ResNet50模型。 还有一版用的是VGG16模型。这三个用的图像embedding的区别是什么呢？
> 
> ### Describe the solution you'd like
> _No response_
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Anything else?
> _No response_
May I ask if the code link for the first version using VGG cannot be found? Is there still a link available

**Comment by DAAworld** [comment]
> May I ask if the code link for the first version using VGG cannot be found? Is there still a link available

The code of  first version was removed from master.You can find it from old branch.

**Comment by codingjaguar** [comment]
Thanks for reporting the issue. What's mentioned in the issue are out-of-date demos. We have developed a new version of image search example in https://github.com/milvus-io/bootcamp/blob/master/bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb, utilizing the latest available open-source models and the just released easy-to-install Milvus Lite (https://github.com/milvus-io/milvus-lite). Let us know how it works for you.
Regarding image models, some of the best ones include [Vision Transformer (ViT)](https://huggingface.co/docs/transformers/en/model_doc/vit) but it really depends on your particular use case (e.g. if cross-modality of text-image search is needed).

Please let us know for any future questions.
