### ISSUE TITLE
[FEATURE]: There are doubts about the search framework using images

### ISSUE THREAD

**Issue by listento123** [milvus-io/bootcamp#1325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Why do we need to pull a MySQL image when creating this image search system with Milvus already in place? The system architecture also includes MySQL. Why is this?
In addition, MySQL is a database, and Milvus is also a database. I don't understand the meaning of pulling MySQL images in building a system, so I'm asking the boss for clarification

**Comment by codingjaguar** [comment]
Please refer to https://github.com/milvus-io/bootcamp/issues/1326.
