### ISSUE TITLE
[FEATURE]: Have you seen a blog post that raises some questions about the current search for images published by GitHub?

### ISSUE THREAD

**Issue by listento123** [milvus-io/bootcamp#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Input the generated images into the image recognition model Resnet50, convert them into vectors, and store them in Milvus. 
Here is the content of the blogger's blog:
Milvus generates an ID for each vector and establishes an index. Afterwards, store the ID and corresponding original image storage path in the CacheDB database.Finally, input an image to be searched, perform object detection and image recognition in sequence, and convert the image to be searched into a vector. Milvus calculates the similarity of vectors and retrieves the IDs of similar images. Based on the IDs, it searches for the corresponding image storage path in the CacheDB database and finally returns the search results to the user.

### Describe the solution you'd like

Why did he use the second database again? Can't Milvus implement this function? I still don't quite understand. Maybe my question is foolish, but I really hope the boss can answer my doubts

**Comment by codingjaguar** [comment]
Thanks for the question. For image search, the reason you need another storage is to store the image bytes (aka blobs). Storing blobs together with vectors and other small primitive data types like ints and strings creates a unique set of technical challenges. We are working on more data types. In the future, Milvus will support blob data type.
