### ISSUE TITLE
docker build  pic-search-webclient  error 

### ISSUE THREAD

**Issue by flydragon2018** [milvus-io/bootcamp#144]
Step 4/17 : RUN yarn
 ---> Running in 67cbcd81a0bd
yarn install v1.21.1
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
warning @material-ui/core > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "@material-ui/styles@^4.9.0" required by "@material-ui/core@^4.7.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1

**Comment by JackLCL** [comment]
The error message indicates that there is a problem with your network connection. You can check your network condition first.

**Comment by flydragon2018** [comment]
error Couldn't find package "@material-ui/styles@^4.9.0" required by "@material-ui/core@^4.7.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1

**Comment by flydragon2018** [comment]
perhaps some dependency changes.
