### ISSUE TITLE
When loading images, the interface shows: Error with 'NoneType' object has no attribute 'count_table' images in this se

### ISSUE THREAD

**Issue by Xiaohanzzz** [milvus-io/bootcamp#147]
When I printing path in the inferface (localhost:8001), it shows
![image](https://user-images.githubusercontent.com/61814887/75946468-2f6f6d80-5ed8-11ea-9f60-1c6f38810f56.png)
And I can continue to load images, but no search results after I upload a new one
![image](https://user-images.githubusercontent.com/61814887/75946553-5d54b200-5ed8-11ea-9056-5b02c069c61a.png)
I don't know how to fix it

**Comment by lxy826076** [comment]
i meet it also,i don't  start milvus server. and you should replace IMAGE_PATH1 to you absolute file path.wish this can help you

**Comment by Xiaohanzzz** [comment]
Thank you for your advice! But I have already change the IMAGE_PATH1, and I successfully load 17000+ images. Do you have some other advice to solve my problem? Thanks
