### ISSUE TITLE
can you add a interface that support one picture to milvus data, not a filepath

### ISSUE THREAD

**Issue by lxy826076** [milvus-io/bootcamp#148]
你好,可以增加一个单张图片加入引擎中的接口吗，而不是传入一个文件路径，如果文件不断加入的话索引需要全部删除然后再重建，这就比较麻烦了，然后能再提供一个根据文件名单个删除索引的接口
Hello, can you add a single picture to the interface in the engine, instead of passing in a file path, if the file is continuously added, the index needs to be deleted and then rebuilt, which is more troublesome, and then you can provide another file based on the file Interface that deletes a single index，thank you.

**Comment by JackLCL** [comment]
Hello, our picture search system code is open source on github, you are welcome to contribute code to this project. 
https://github.com/milvus-io/bootcamp/tree/master/solutions/pic_search
