### ISSUE TITLE
milvus.grpc.SearchParam.partition_tag_array' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 

### ISSUE THREAD

**Issue by zxzxde** [milvus-io/bootcamp#158]
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:584] String field 'milvus.grpc.SearchParam.partition_tag_array' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Comment by JackLCL** [comment]
We have solved this problem in wechat.
