### ISSUE TITLE
accuracy 0.0 % for 1 million benchmark testing 

### ISSUE THREAD

**Issue by yisampi** [milvus-io/bootcamp#169]
accuracy 0.0 % for 1 million benchmark testing 

#  python3 main.py --show
['example_collection', 'ann_1m_sq8']
# python3 main.py --collection ann_1m_sq8 --rows
1000000
# python3 main.py --collection ann_1m_sq8 --describe_index
(collection_name='ann_1m_sq8', index_type=<IndexType: IVF_SQ8>, params={'nlist': 16384})
# python3 main.py --collection=ann_1m_sq8 --search_param 64 --recall
collection name: ann_1m_sq8 query list: 500 topk: 200 search_params: {'nprobe': 64}
time_search =  0.11832094192504883
total accuracy 0.0 %
total accuracy 0.0 %
total accuracy 0.0 %
total accuracy 0.0 %

**Comment by Bennu-Li** [comment]
The ground_truth data link is wrong, we will give the correct link later

**Comment by Bennu-Li** [comment]
We have modified the data link, you can update the project and download new data for testing.

**Comment by yisampi** [comment]
thanks

**Comment by Bennu-Li** [comment]
I hope above answers did help!
Could you please help us to do a quick survey regarding the product? We really appreciate it if you could give some feedback for Milvus.
English questionnaire address：https://www.surveymonkey.com/r/YH7KPVF
中文问卷地址：https://www.surveymonkey.com/r/YPQCYMR

**Comment by yisampi** [comment]
i have download the gnd data from https://pan.baidu.com/s/1KGlBiJvuGpqjbZOIpobPUg
but it still accuracy 0.0 %.

**Comment by yisampi** [comment]
i find the ground_truth data for  100 million data is wrong too.
can you list the ground_truth data link  for 1 million and  100 million here?
thanks

**Comment by Bennu-Li** [comment]
sift1m link: https://pan.baidu.com/s/1cuEBw29rb4GEr4QWvFVWzQ    extraction code: l015 
sift100m link: https://pan.baidu.com/s/141SqPE5uRgT2o0KpcePcEQ   extraction code: hg8q

**Comment by Bennu-Li** [comment]
The sift1m data also needs to be downloaded again. Did you download the original data again？

**Comment by Bennu-Li** [comment]
I submit the update to the 0.7.0 branch

**Comment by yisampi** [comment]
thanks.
I have finished the sift1m test. and thank you again.
# python3 main.py --collection=ann_1m_sq8 --search_param 128 --recall
collection name: ann_1m_sq8 query list: 500 topk: 200 search_params: {'nprobe': 128}
time_search =  4.5372514724731445
total accuracy 100.0 %
total accuracy 100.0 %
total accuracy 100.0 %
total accuracy 100.0 %
# python3 main.py --collection=ann_1m_sq8 --search_param 128 --performance
load query: 1 time_load =  0.11037635803222656
1 1 0.023580312728881836
1 1 0.02660393714904785
1 10 0.026822805404663086
1 100 0.031226634979248047
1 500 0.0310671329498291
load query: 10 time_load =  0.09685111045837402
10 1 0.05784893035888672
10 1 0.05975604057312012
10 10 0.0630495548248291
10 100 0.06335020065307617
10 500 0.06578254699707031
load query: 100 time_load =  0.1086127758026123
100 1 0.4272322654724121
100 1 0.43965816497802734
100 10 0.42134785652160645
100 100 0.42618250846862793
100 500 0.5022156238555908
load query: 200 time_load =  0.09475040435791016
200 1 0.7351689338684082
200 1 0.7119474411010742
200 10 0.771979570388794
200 100 0.7532305717468262
200 500 1.0156927108764648
search_vec_list done !

But get the gnd data（sift100m link: https://pan.baidu.com/s/141SqPE5uRgT2o0KpcePcEQ  extraction code: hg8q） for sift100m again , the accuracy  is still 0.0 %.
So do I have to download the data again:
or can you list the links of sift100m here again.？
thanks very much.

**Comment by Bennu-Li** [comment]
The sift10m data storage format is uint8, so you need to modify IS_UINT8 in the config.py to True. 
![image](https://user-images.githubusercontent.com/53458891/79708487-14bf4f80-82f2-11ea-895d-819c7f2ae1aa.png)

**Comment by yisampi** [comment]
@Bennu-Li 
更新完gnd data后 1亿的数据集准确性测试 acc还是0 请帮忙看看 谢谢 

# python36 main.py --collection=ann_100m_sq8 --search_param 128 --recall
collection name: ann_100m_sq8 query list: 500 topk: 200 search_params: {'nprobe': 128}
time_search =  4.525655746459961
total accuracy 0.0 %
total accuracy 0.0 %
total accuracy 0.0 %
total accuracy 0.0 %
You have new mail in /var/spool/mail/root

# python36 main.py --collection ann_100m_sq8 --rows
100000000

# python36 main.py --collection ann_100m_sq8 --describe_index
(collection_name='ann_100m_sq8', index_type=<IndexType: IVF_SQ8>, params={'nlist': 16384})

# grep IS_UINT8  config.py 
IS_UINT8 = True

**Comment by Bennu-Li** [comment]
I need more operation information. Please join the Milvus technical discussion group for further communication. 
![image](https://user-images.githubusercontent.com/53458891/79960762-5f8ac400-84b8-11ea-8d72-7fb35e42b609.png)

**Comment by Bennu-Li** [comment]
I need more operation information. Please join the Milvus technical discussion group for further communication.
![image](https://user-images.githubusercontent.com/53458891/79962601-d628c100-84ba-11ea-987c-d8edffdd5d30.png)

**Comment by yisampi** [comment]
@Bennu-Li 人满加不进去了

**Comment by Bennu-Li** [comment]
@yisampi 
加这个群吧
![image](https://user-images.githubusercontent.com/53458891/80065074-17c57480-856c-11ea-92aa-3b2c98b38c67.png)
