### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Aissue** [milvus-io/bootcamp#182]
您好，请问您这边图片向量化vgg的python实现，其中keras和TensorFlow的版本分别是？python的版本呢？还望赐教，因为我这边总是版本冲突...

**Comment by JackLCL** [comment]
这些版本信息你可以在requirement.txt里面看到。

**Comment by Aissue** [comment]
> 这些版本信息你可以在requirement.txt里面看到。

收到，我试试，非常感谢
