### ISSUE TITLE
milvus 0.8.0 导入图片，milvus报错

### ISSUE THREAD

**Issue by Seven2Nine** [milvus-io/bootcamp#194]
Invalid index type: 0. Make sure the index type is in IndexType list.
Request failed with code: Error code(30105): Invalid index type: 0. Make sure the index type is in IndexType list.

**Comment by JackLCL** [comment]
Can you provide more detailed information about your problem?  Welcome to join our wechat group to communicate more.
![image](https://user-images.githubusercontent.com/53512883/81387520-6a488880-9149-11ea-8fd4-2a1da516335f.png)

**Comment by q351941406** [comment]
可能是端口问题,要放行以下端口:35000、5000、19530、8001、9000
