### ISSUE TITLE
Benchmark testing on cpu is slow extremely

### ISSUE THREAD

**Issue by wildpalss** [milvus-io/bootcamp#229]
I performced 50 million benchmark testing on three servers ,according to the 100 million testing,one virtual machine and two physical machines  with 12 and 24 cores, respectively.My Version of Milvus is 0.9.0 CPU. The CPU model is e5-2620 V3.
However,i gained a incomprehensible  result. The virtual machine is three times faster than physical machines while nprobe is 1000.Execute the query on the virtual machine cost 5 seconds.
Can you slove this problem and find the reason with me?

**Comment by Bennu-Li** [comment]
Can you provide more detailed configuration information？

**Comment by wildpalss** [comment]
Which aspect of configuration information?server or config of the milvus?
