### ISSUE TITLE
建立集合中的向量数为0

### ISSUE THREAD

**Issue by nobody-cheng** [milvus-io/bootcamp#298]
安装教程导入亿级可以复现，
使用自己的数据  shape： 20000000 * 1 * 2048
1. 进入 `milvus_sift1m` 目录，运行如下脚本在 Milvus 中创建集合并建立索引：

```
python main.py --collection reid_2kw_sq8 --dim 2048 -c
python main.py --collection reid_2kw_sq8 --index sq8 --build 
```
![建立集合](https://user-images.githubusercontent.com/34908468/92356148-304bbb00-f118-11ea-9fa2-65d567109044.jpg)

2. 导入数据和查看表信息，及手动建立索引
'''
python main.py --collection=reid_2kw_sq8 --load
python main.py --collection=reid_2kw_sq8 --rows
python main.py --collection=reid_2kw_sq8 --index=sq8 --build 
'''
![导入数据](https://user-images.githubusercontent.com/34908468/92356562-e6afa000-f118-11ea-9bb0-52be343120f8.jpg)

3. 数据库查询--ERROR，查询信息无输出，但是查询 ann_100m_sq8 有输出
'''
cd /var/lib/milvus/db/
sqlite3 meta.sqlite
select * from TableFiles where table_id='reid_2kw_sq8';
'''
![数据库None](https://user-images.githubusercontent.com/34908468/92356953-97b63a80-f119-11ea-8329-0663d0486e2c.jpg)
![数据库无输出](https://user-images.githubusercontent.com/34908468/92356957-984ed100-f119-11ea-8c14-329e8612ae9b.jpg)

![数据库](https://user-images.githubusercontent.com/34908468/92358634-5d9a6800-f11c-11ea-9573-1e5210288911.jpg)

config
```
from milvus import *
import os

MILVUS_HOST = "192.168.1.85"
MILVUS_PORT = 19560

# create table param
INDEX_FILE_SIZE = 2048
METRIC_TYPE = MetricType.L2


# index IVF param
NLIST = 16384
PQ_M = 12

#index NSG param
SEARCH_LENGTH = 45
OUT_DEGREE = 50
CANDIDATE_POOL = 300
KNNG = 100

#index HNSW param
HNSW_M = 16
EFCONSTRUCTION = 500



# NL_FOLDER_NAME = '/data/lcl/200_ann_test/source_data'


# insert param
FILE_TYPE = 'npy'
FILE_NPY_PATH = '/data/workspace/lym/milvus_test/data/sift_data/sift100m/data'
FILE_CSV_PATH = '/data1/lym/dataset_test/csv_dataset'
FILE_FVECS_PATH = '/mnt/data/base.fvecs'
FILE_BVECS_PATH = '/data/workspace/lym/milvus_test/data/sift_data/bigann_base.bvecs'
# VECS_VEC_NUM = 1000000000
VECS_VEC_NUM = 20000 
VECS_BASE_LEN = 20000
if_normaliz = False



# performance param
NQ_FOLDER_NAME = '/data/workspace/lym/milvus_test/data/sift_data/query_data'
PERFORMANCE_FILE_NAME = 'performance'

nq_scope = [1,10,100,500,1000]  # query size
#nq_scope = [1000, 1000]
topk_scope = [1, 1,10,100,500]  # top k
#nq_scope = [1, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800]
#topk_scope = [1,1, 20, 50, 100, 300, 500, 800, 1000]
IS_CSV = False
IS_UINT8 = True




#recall param
recall_topk = 500
compute_recall_topk = [1, 10, 100,500]
recall_nq = 500

recall_vec_fname = '/data/workspace/lym/milvus_test/data/sift_data/query_data/query.npy'
#recall_vec_fname = '/data/workspace/lym/milvus_08_bootcamp/bootcamp/benchmark_test/scripts/data/sift1m/data/binary_128d_00000.npy'
GT_FNAME_NAME = '/data/workspace/lym/milvus_test/data/sift_data/sift100m/gnd/ground_truth_100M.txt'


recall_res_fname = 'recall_result'
recall_out_fname = 'recall_result/recall_compare_out'
```

**Comment by nobody-cheng** [comment]
> 安装教程导入亿级可以复现，
server_version:  0.10.2
client_version:  0.2.14
> 使用自己的数据 shape： 20000000 * 1 * 2048
> 
> 1. 进入 `milvus_sift1m` 目录，运行如下脚本在 Milvus 中创建集合并建立索引：
> 
> ```
> python main.py --collection reid_2kw_sq8 --dim 2048 -c
> python main.py --collection reid_2kw_sq8 --index sq8 --build 
> ```
> 
> ![建立集合](https://user-images.githubusercontent.com/34908468/92356148-304bbb00-f118-11ea-9fa2-65d567109044.jpg)
> 
> 1. 导入数据和查看表信息，及手动建立索引
>    '''
>    python main.py --collection=reid_2kw_sq8 --load
>    python main.py --collection=reid_2kw_sq8 --rows
>    python main.py --collection=reid_2kw_sq8 --index=sq8 --build
>    '''
>    ![导入数据](https://user-images.githubusercontent.com/34908468/92356562-e6afa000-f118-11ea-9bb0-52be343120f8.jpg)
> 2. 数据库查询--ERROR，查询信息无输出，但是查询 ann_100m_sq8 有输出
>    '''
>    cd /var/lib/milvus/db/
>    sqlite3 meta.sqlite
>    select * from TableFiles where table_id='reid_2kw_sq8';
>    '''
>    ![数据库None](https://user-images.githubusercontent.com/34908468/92356953-97b63a80-f119-11ea-8329-0663d0486e2c.jpg)
>    ![数据库无输出](https://user-images.githubusercontent.com/34908468/92356957-984ed100-f119-11ea-8c14-329e8612ae9b.jpg)

![数据库](https://user-images.githubusercontent.com/34908468/92357139-f380c380-f119-11ea-97fd-380e2cdb1500.jpg)

**Comment by arya0812** [comment]
Since you only split 20 million 2048-dimensional vectors into 4 .npy files, there might exist failures when you insert them. There are two ways to check, first, you can check the logs under `milvus/logs`, and second you can add some print to examine if there are any errors during insertion. 
Milvus can insert up to 256M of memory at a time, thus we recommend you store fewer vectors per .npy file, such as 40,000. About counting size, please use [Milvus sizing tools](https://milvus.io/tools/sizing).

**Comment by nobody-cheng** [comment]
> Since you only split 20 million 2048-dimensional vectors into 4 .npy files, there might exist failures when you insert them. There are two ways to check, first, you can check the logs under `milvus/logs`. Second, try to add some print to examine if there are any errors during insertion.
> Milvus can insert up to 256M of memory at a time, thus we recommend you store fewer vectors per .npy file, such as 40,000. About counting size, please use [Milvus sizing tools](https://milvus.io/tools/sizing).


I have split 1000 .npy, ERROR
```
Retry to connect server 127.0.0.1:19530 failed.

Addr [127.0.0.1:19530] insert
Excepted error: Fail connecting to server on 127.0.0.1:19530. Timeout
        {'API start': '2020-09-07 09:13:14.654320', 'Exception': '2020-09-07 09:14:44.656580'}
```
![timeout](https://user-images.githubusercontent.com/34908468/92372084-05b92c80-f12f-11ea-9219-2312a17802a6.jpg)

thanks

**Comment by arya0812** [comment]
First, using `docker logs <container id>` to check the status of Milvus. Then, you could try to edit **MILVUS_HOST** to IP address 192.168.x.y. Remember to drop the failed collection or resume loading from 24.npy.

**Comment by arya0812** [comment]
Cheng,
You could join our Wechat group chat for more efficient communication :)
![58c9e277-d89c-4618-b6ef-bbb8326e95aa](https://user-images.githubusercontent.com/22544815/92374515-6a29bb00-f132-11ea-8b38-32f6bb202ec5.jpg)
