### ISSUE TITLE
数据下载方式咨询

### ISSUE THREAD

**Issue by sty945** [milvus-io/bootcamp#302]
请问数据的下载方式除了百度云之外，是否还有其它的下载方式？
百度云限速下载速度实在太慢，非常感谢

如下面的数据地址：
```
100 万测试数据集下载地址：链接：https://pan.baidu.com/s/1TSjGaAlQOQm3PpJfZ6dtPQ 提取码：2x5o
```

**Comment by Bennu-Li** [comment]
你可以加入 milvus 技术交流群，我们会有相关人员给你发送数据。
![image](https://user-images.githubusercontent.com/53458891/93175578-6addd500-f762-11ea-945b-97464a1fc060.png)
