### ISSUE TITLE
demo docker构建后不成功，构建会报错

### ISSUE THREAD

**Issue by angleGhost** [milvus-io/bootcamp#325]
包报错信息：
Step 4/17 : RUN yarn
 ---> Running in 7e453e9bd89a
yarn install v1.22.4
info No lockfile found.

**Comment by JackLCL** [comment]
欢迎加入我们的微信技术交流群进行交流。
![image](https://user-images.githubusercontent.com/53512883/96104486-7c560080-0f0b-11eb-8fac-d38898c94daf.png)
