### ISSUE TITLE
1亿大小的benchmark的recall都是0

### ISSUE THREAD

**Issue by mindayao** [milvus-io/bootcamp#328]
按照说明操作，在 --recall的命令后，输出的是0%的准确率

![image](https://user-images.githubusercontent.com/14901821/96701704-7bb5e200-13c3-11eb-8bf7-aa3fb85af834.png)

而对100万的benchmark的过程是正常的
![image](https://user-images.githubusercontent.com/14901821/96702753-a5bbd400-13c4-11eb-91e3-511992fa395f.png)

**Comment by Bennu-Li** [comment]
![image](https://user-images.githubusercontent.com/53458891/97126471-dfe4f700-1771-11eb-94e0-a916c54a4c1e.png)
