### ISSUE TITLE
图片搜索报错，http://40.73.38.81/无法访问

### ISSUE THREAD

**Issue by white8897** [milvus-io/bootcamp#332]
![image](https://user-images.githubusercontent.com/52773566/97253522-9f57ad00-1847-11eb-868e-6110ffa68f3a.png)
![image](https://user-images.githubusercontent.com/52773566/97254687-df1f9400-1849-11eb-9d52-e62f11317e76.png)

**Comment by JackLCL** [comment]
@white8897 
Now the latest demo address for searching images is http://116.228.99.250:8004/

**Comment by white8897** [comment]
![image](https://user-images.githubusercontent.com/52773566/97254335-1ccfed00-1849-11eb-8819-68e7f55280b5.png)
![image](https://user-images.githubusercontent.com/52773566/97254560-9962cb80-1849-11eb-97e9-aa1737ef8775.png)

**Comment by white8897** [comment]
您好，部署流程我是按照项目readme里的流程走的，为什么最后前端报错了呢？具体错误在前边两张图里。

**Comment by white8897** [comment]
请问http://116.228.99.250:8004/的demo，milvus是使用的CPU版还是GPU版？

**Comment by JackLCL** [comment]
> 请问[http://116.228.99.250:8004/的demo，milvus是使用的CPU版还是GPU版？](http://116.228.99.250:8004/%E7%9A%84demo%EF%BC%8Cmilvus%E6%98%AF%E4%BD%BF%E7%94%A8%E7%9A%84CPU%E7%89%88%E8%BF%98%E6%98%AFGPU%E7%89%88%EF%BC%9F)

CPU版

**Comment by JackLCL** [comment]
> 您好，部署流程我是按照项目readme里的流程走的，为什么最后前端报错了呢？具体错误在前边两张图里。

你加到我们的交流群里，我们帮你分析一下。
![image](https://user-images.githubusercontent.com/53512883/97255191-0cb90d00-184b-11eb-8e49-9845ab2efee6.png)

**Comment by xyzonline** [comment]
同样问题，只是提示的字段稍有不同：Error with 'NoneType' object has no attribute 'count_entities' images in this set，也是调用WEB服务出500错误：500 Internal Server Error。
不太懂怎么去排查。

**Comment by xyzonline** [comment]
解决的能不能贴一下思路出来，你们这个群又是超期，能不能提供个长期点的。

**Comment by xyzonline** [comment]
把代码拉下来了看看，目前我的情况是图片路径搞错了，现在可以TRAIN了，不过没进度，不清楚还要多长时间可以到下一步。
之前出500错误，就是train没有进行，估计是没有训练好的数据，执行process没有数据就出错了。
$ docker run -d --name zilliz_search_images_demo \
-v ${IMAGE_PATH1}:/tmp/pic1 \
-v ${IMAGE_PATH2}:/tmp/pic2 \
这里${IMAGE_PATH1} ${IMAGE_PATH2} 要设置成本地放图片的路径，比如 -v /home/lab/picdata:/tmp/pic1 \

**Comment by xyzonline** [comment]
又来了，之前想训练6X万图片，结果用CPU版跑得太慢，一天后进度都卡着没进展，现在换成几百张图，训练完后，又出提示：
Error with 'NoneType' object has no attribute 'count_entities' images in this set
558/558
然后search后，又来500错误：
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by JackLCL** [comment]
Please check the app.log in webserver container to locate the reason.
