### ISSUE TITLE
demo容器运行失败，searchvideodemo_demo_1 not up! ---Exit 1

### ISSUE THREAD

**Issue by tendrillion** [milvus-io/bootcamp#339]
系统版本：ubuntu18.04
根据readme操作，但是容器运行失败。
$ docker-compose up -d
searchvideodemo_redis_1 is up-to-date
searchvideodemo_minio_1 is up-to-date
searchvideodemo_milvus_1 is up-to-date
searchvideodemo_api_1 is up-to-date
Starting searchvideodemo_demo_1 ... 
Starting searchvideodemo_demo_1 ... done

$ docker-compose ps
searchvideodemo_api_1      /usr/bin/gunicorn3 -w 4 -b ...   Up       0.0.0.0:5002->5000/tcp                          
searchvideodemo_demo_1     /bin/bash -c /usr/share/ng ...   Exit 1                                                   
searchvideodemo_milvus_1   /var/lib/milvus/docker-ent ...   Up       0.0.0.0:19530->19530/tcp, 0.0.0.0:8080->8080/tcp
searchvideodemo_minio_1    /usr/bin/docker-entrypoint ...   Up       0.0.0.0:9000->9000/tcp                          
searchvideodemo_redis_1    docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp     

读取docker log如下：
$ docker-compose logs
Attaching to searchvideodemo_demo_1, searchvideodemo_api_1, searchvideodemo_milvus_1, searchvideodemo_redis_1, searchvideodemo_minio_1
demo_1    | 2020/11/18 06:27:55 [emerg] 1#1: host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11
demo_1    | nginx: [emerg] host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11
demo_1    | 2020/11/18 08:34:34 [emerg] 1#1: host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11
demo_1    | nginx: [emerg] host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11
demo_1    | 2020/11/18 08:40:05 [emerg] 1#1: host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11
demo_1    | nginx: [emerg] host not found in upstream "search-video-demo_api_1" in /etc/nginx/conf.d/client.conf:11

**Comment by JackLCL** [comment]
Please check the log of search-video-demo_api_1 docker.
