### ISSUE TITLE
你们会开源吗？

### ISSUE THREAD

**Issue by stackOverMind** [milvus-io/bootcamp#34]
产品很棒，我一直在寻找类似产品。未来是否会收费？是否会开源

**Comment by gujun720** [comment]
你好。感谢你对我们产品的肯定。请问你是打算在什么场景下使用 Milvus 呢？方便的话，请多给我们一些反馈，我们期待每一个用户的意见和建议。

Milvus 是由 ZILLIZ 公司开发的软件产品。我们预计最早会在今年四季度发布开源的 Milvus 。现在提供的试用版本，就是未来开源版本的基础。目前我们正忙着梳理版本功能，增加代码文档说明，提高代码质量等工作。

我们计划采用 Apache 2.0 的模式发布开源版 Milvus 。因此，目前提供的试用版 Milvus 也允许被集成到商业项目中去。不过只有购买软件订阅服务，才能获得我们的企业级支持。

希望我们回答了你的疑问 ^_^
