### ISSUE TITLE
im2recipe solution failed to query by uploading an image in the web front

### ISSUE THREAD

**Issue by douglarek** [milvus-io/bootcamp#346]
I just tried [im2recipe](https://github.com/milvus-io/bootcamp/tree/master/solutions/im2recipe) demo. And I run into its python api(`uvicorn main:app --port=8999 --host=0.0.0.0`, its host is `172.16.200.22`), it works:

![image](https://user-images.githubusercontent.com/1488134/100312954-8aa93900-2fee-11eb-9189-bd225756a5dd.png)

But its web front didn't work (`docker run -d -p 9898:80 -e API_URL=http://172.16.200.22:8999 zilliz/milvus-search-food-recipes:lates`):

![image](https://user-images.githubusercontent.com/1488134/100312828-4027bc80-2fee-11eb-8399-0e3b229a97cb.png)

**Comment by Bennu-Li** [comment]
I have updated the code,  you can try again.

**Comment by douglarek** [comment]
> I have updated the code, you can try again.

thanks, it works
