### ISSUE TITLE
100m performance test crashed

### ISSUE THREAD

**Issue by douglarek** [milvus-io/bootcamp#359]
I run into [100m performance test](https://github.com/milvus-io/bootcamp/blob/0.11.0/benchmark_test/lab2_sift1b_100m.md) with HNSW index type.

When I executed `python3 main.py --collection=ann_100m_sq8 --search_param 128 --performance` about some seconds, it crashed:

```
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1607074756.992817652","description":"Error received from peer ipv6:[::1]:19530","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
```

I checked milvus server docker logs:

```
[2020-12-04 17:34:04,705][ERROR][SERVER][TakeToExecute][query] Req failed with code: Error: Illegal search params
```

And milvus docker instance was terminated.

**Comment by jingkl** [comment]
Check the collection and query parameters

**Comment by jingkl** [comment]
If you have any questions, please contact me or join the Milvus group
