### ISSUE TITLE
使用Milvus和bert构建文本搜索引擎出错，example例子能正常运行

### ISSUE THREAD

**Issue by hurun** [milvus-io/bootcamp#369]
Linux：  version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018
milvus:   0.10.0
pymilvus:   2.13
python:  3.6
已安装readme要求配置环境，正常能打开搜索页面，输入搜索词没有搜索结果，返回No results found，
重复几次后，main.py报错退出，输出内容如下：

(py3.6) [root@localhost Milvus-bert-server]# python main.py --collection test11 --title data/title.txt --version data/version.txt --load
Status(code=0, message='Add vectors successfully!')
unable to connect to the database
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main()
  File "main.py", line 31, in main
    milvus_bert.import_data(table_name, title_dir, version_dir)
  File "/home/jx3/bootcamp/solutions/Textsys/Milvus-bert-server/src/milvus_bert.py", line 107, in import_data
    import_to_pg(collection_name,ids,title_dir,version_dir)
  File "/home/jx3/bootcamp/solutions/Textsys/Milvus-bert-server/src/milvus_bert.py", line 40, in import_to_pg
    cur = conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
(py3.6) [root@localhost Milvus-bert-server]# python main.py --collection test11 --title data/title.txt --version data/version.txt --load
Status(code=0, message='Add vectors successfully!')
unable to connect to the database
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main()
  File "main.py", line 31, in main
    milvus_bert.import_data(table_name, title_dir, version_dir)
  File "/home/jx3/bootcamp/solutions/Textsys/Milvus-bert-server/src/milvus_bert.py", line 107, in import_data
    import_to_pg(collection_name,ids,title_dir,version_dir)
  File "/home/jx3/bootcamp/solutions/Textsys/Milvus-bert-server/src/milvus_bert.py", line 40, in import_to_pg
    cur = conn.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by jingkl** [comment]
1. It is clear that the database was not successfully linked
2. You need to install Postgresql first
3. After installation, it is necessary to install the README for configuration
4. Successfully test whether postgresql can be linked

**Comment by jingkl** [comment]
Install the README to configure the user name and password after installation

**Comment by hurun** [comment]
> Install the README to configure the user name and password after installation

already do what you say
1.
(py3.6) [root@localhost milvus]# ps -ef |grep post
root      2399  9571  0 10:36 pts/5    00:00:00 grep --color=auto post
postgres 27078     1  0 Dec22 ?        00:00:00 /usr/pgsql-13/bin/postmaster -D /var/lib/pgsql/13/data/
postgres 27083 27078  0 Dec22 ?        00:00:00 postgres: logger 
postgres 27088 27078  0 Dec22 ?        00:00:00 postgres: checkpointer 
postgres 27089 27078  0 Dec22 ?        00:00:00 postgres: background writer 
postgres 27090 27078  0 Dec22 ?        00:00:00 postgres: walwriter 
postgres 27091 27078  0 Dec22 ?        00:00:00 postgres: autovacuum launcher 
postgres 27092 27078  0 Dec22 ?        00:00:00 postgres: stats collector 
postgres 27093 27078  0 Dec22 ?        00:00:00 postgres: logical replication launcher 


2. src/config.py
import os

MILVUS_HOST = os.getenv("MILVUS_HOST", "127.0.0.1")
MILVUS_PORT = os.getenv("MILVUS_PORT", 19530)


PG_HOST = os.getenv("PG_HOST", "127.0.0.1")
PG_PORT = os.getenv("PG_PORT", 5432)
PG_USER = os.getenv("PG_USER", "postgres")
PG_PASSWORD = os.getenv("PG_PASSWORD", "notifier123")   ## replace password
PG_DATABASE = os.getenv("PG_DATABASE", "testdb")
DEFAULT_TABLE = os.getenv("DEFAULT_TABLE", "test11")

**Comment by jingkl** [comment]
Do you have any remote postgresql configuration, https://blog.csdn.net/u014698745/article/details/86612511, and then link the postgresql through the virtual environment
