### ISSUE TITLE
使用mishards搭建集群实例后，只读节点一直没有被调用

### ISSUE THREAD

**Issue by orange-jams** [milvus-io/bootcamp#370]
使用mishards搭建了集群（服务器A和B），包含一个写节点（A上）、一个读节点（B上）、共享存储（A上）、mishards（A上），向量的量级在20万，建立好索引后，连续高并发调用发现search指令永远是由A上的写节点在执行。

**Comment by Bennu-Li** [comment]
Which version of milvus？

**Comment by orange-jams** [comment]
> Which version of milvus？

0.10.4

**Comment by Bennu-Li** [comment]
Can you attach the mishards configuration file?

**Comment by orange-jams** [comment]
> Can you attach the mishards configuration file?

服务器A的ip：10.11.12.1
服务器B的ip：10.11.12.2
version: "2.3"
services:
    mishards:
        restart: always
        image: mishards:0.10.4
        ports:
            - "0.0.0.0:19531:19531"
            - "0.0.0.0:19532:19532"
              #volumes:
              #- /tmp/milvus/db:/tmp/milvus/db
            # - /tmp/mishards_env:/source/mishards/.env
        command: ["python", "mishards/main.py"]
        environment:
            FROM_EXAMPLE: 'true'
            SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:milvusroot@10.11.12.1:3306/milvus?charset=utf8mb4
            DEBUG: 'true'
            SERVER_PORT: 19531
            WOSERVER: tcp://10.11.12.1:19530
            DISCOVERY_PLUGIN_PATH: static
            DISCOVERY_STATIC_HOSTS: 10.11.12.1, 10.11.12.2
            DISCOVERY_STATIC_PORT: 19530

**Comment by orange-jams** [comment]
我今天又测试了一下，发现这次在search时只会调用到只读节点。

**Comment by Bennu-Li** [comment]
This is because your total data is less than index_file_size, resulting in only one segment in the collection. According to mishards' strategy, different segments will be assigned to different nodes for search. If there is only one segment, only one node will be responsible for searching.
