### ISSUE TITLE
搭建以图搜图前端报错

### ISSUE THREAD

**Issue by fenghuolianying** [milvus-io/bootcamp#371]
使用CPU milvus:0.11.0-cpu-d101620-4c44c0   milvusbootcamp/pic-search-webserver:0.10.0  milvusbootcamp/pic-search-webclient:0.2.0 前端报错

<img width="537" alt="WX20201224-114504@2x" src="https://user-images.githubusercontent.com/48470125/103058622-a435a480-45dd-11eb-85ab-ed44b87c2635.png">

**Comment by JackLCL** [comment]
Please check the app.log in webserver container to locate the reason.
