### ISSUE TITLE
智能问答系统，新增问题答案时，postgres报错

### ISSUE THREAD

**Issue by r0ckyang** [milvus-io/bootcamp#373]
postgres 报 CREATE INDEX 错误，定位到pg_operating中的build_pg_index函数，尝试将其中sql语句CREATE INDEX修改为CREATE INDEX IF NOT EXISTS，报错消失，但出现另外一种问题，搜索结果不准确了。所以，现在维护时，只能先完全清除之前的数据，然后再一次全部导入，无法进行增量维护。

**Comment by Bennu-Li** [comment]
你这样修改是可以的，你说的搜索结果不准确了是哪一步搜索时不准确了呢，milvus里搜索有误还是pg呢？

**Comment by r0ckyang** [comment]
又测试了几次，这样修改可以，没有出现搜索结果不准确的问题，谢谢回复。
