### ISSUE TITLE
Code for movie-taste-demo

### ISSUE THREAD

**Issue by jayurbain** [milvus-io/bootcamp#390]
The graph recommend demo: bootcamp/EN_solutions/graph_based_recommend/

uses a docker file: tumao/movie-taste-demo

Is the code for movie-taste-demo available?

Great demo

Thanks,
Jay

**Comment by shanghaikid** [comment]
@jayurbain which code do you need, backend code or the frontend?

**Comment by jayurbain** [comment]
I would like the whole application. I believe your repository has the full back-end, but it does not have the web app.

Thanks,
Jay

**Comment by jayurbain** [comment]
Hi,

I was trying to run your whole application so I could experiment with it. I
believe
your github repository has the backend, but it does not have the frontend.

Thanks,
Jay Urbain

**Comment by shanghaikid** [comment]
@jayurbain here it is, very simple web ui made using react. 
https://github.com/milvus-io/milvus-demo-movie-taste

**Comment by shanghaikid** [comment]
@jayurbain  here it is, very simple web ui . 
https://github.com/zilliztech/milvus-demo-movie-taste

**Comment by jayurbain** [comment]
Thanks.

Jay
