### ISSUE TITLE
Encountered problem while using MolSearch

### ISSUE THREAD

**Issue by xiao-zhang** [milvus-io/bootcamp#409]
在使用化学式检索时出现了Error with 'NoneType' object has no attribute 'count_entities' Molecular Formula错误，求问怎么解决啊

**Comment by xiao-zhang** [comment]
在从smiles-data导入test_1w.smi数据时出现的这个错误

**Comment by JackLCL** [comment]
请确认一下milvus的版本和pymilvus的版本是否是匹配的？

**Comment by shiyu22** [comment]
not activate, closed.
