### ISSUE TITLE
Baidu File Hosting

### ISSUE THREAD

**Issue by filip-halt** [milvus-io/bootcamp#414]
Lab1_sift1b_1m and Lab2_sift1b_100m have their data files hosted on Baidu, making it near impossible to download in the US. Is there any chance these files can be uploaded on something like Dropbox/GoogleDrive?

**Comment by shiyu22** [comment]
As for Lab1_sift1b_1m, you can download the data on GoogleDrive:

1 million test data: https://drive.google.com/file/d/1lwS6iAN-ic3s6LLMlUhyxzPlIk7yV7et/view?usp=sharing
Query data: https://drive.google.com/file/d/17jPDk93PQsB5yGh1J1YD9N7X8jvPEUQL/view?usp=sharing
Ground truth: https://drive.google.com/file/d/1vBP9mKu5oxyognHtOBBRtLvyPvo8cCp0/view?usp=sharing

**Comment by jingkl** [comment]
As for Lab2_sift1b_100m, you can download the data on GoogleDrive: https://drive.google.com/drive/folders/1sXf9W8wjJ2vk71slx105zQBctRNYwWuA?usp=sharing
