### ISSUE TITLE
Distributed solution

### ISSUE THREAD

**Issue by N-Kingsley** [milvus-io/bootcamp#415]
个人对这块不太了解，请问基于K8s和基于Mishards部署分布式milvus的区别是什么呢？

**Comment by Bennu-Li** [comment]
无论是否基于 K8 部署，分布式都有用到 mishards。mishards 是 Milvus 集群分片中间件，其内部处理请求转发、读写分离等。比如说在查询时，Mishards 会将数据分发给各数据节点。而k8s是用来管理和部署容器的一个工具。
具体详情可参考：[mishards](https://github.com/milvus-io/milvus/blob/master/shards/README_CN.md)
                       [k8s](https://kubernetes.io/zh/docs/concepts/overview/what-is-kubernetes/)

**Comment by shiyu22** [comment]
not activate, closed.
