### ISSUE TITLE
关于基准测试

### ISSUE THREAD

**Issue by leslielee1997** [milvus-io/bootcamp#416]
请问可以将SIFT1B测试脚本添加到基准测试中吗？
此外，我发现milvus version1.0的基准测试脚本尚未更新，并且似乎停留在0.10.x版本。

**Comment by Bennu-Li** [comment]
目前已将测试更新到1.0了。 sift1B 的数据集是可以用脚本直接测试的。导入数据时在配置文件 config.py 将数据文件格式修改为 bvecs。然后将导入数据目录指向原始的 sift1B 的数据集。
