### ISSUE TITLE
以图搜视频，docker-compose up -d启动

### ISSUE THREAD

**Issue by Sunyingbin** [milvus-io/bootcamp#431]
按照文档操作启动之后，8001的前端容器没有启动
![image](https://user-images.githubusercontent.com/23546166/114810186-20970200-9dde-11eb-8b48-5872b1211532.png)
但是如上显示五个done了，docker ps看没有对应的容器启动：
![image](https://user-images.githubusercontent.com/23546166/114810235-373d5900-9dde-11eb-9913-c6a9b918b421.png)
如上，只有四个容器启动

**Comment by JackLCL** [comment]
你用docker ps -a看看那个没有启动成功的docker，然后用docker logs看看日志。

**Comment by Sunyingbin** [comment]
> 你用docker ps -a看看那个没有启动成功的docker，然后用docker logs看看日志。

![image](https://user-images.githubusercontent.com/23546166/114821462-3105a780-9df3-11eb-92e2-8c86cbd72c8d.png)
![image](https://user-images.githubusercontent.com/23546166/114821631-71652580-9df3-11eb-905d-7d73cb6d52e2.png)

**Comment by Sunyingbin** [comment]
> 你用docker ps -a看看那个没有启动成功的docker，然后用docker logs看看日志。

![image](https://user-images.githubusercontent.com/23546166/114821739-98235c00-9df3-11eb-8e24-b3a8e86f6bac.png)

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/114822654-fa309100-9df4-11eb-8e01-54304d5b692a.png)

**Comment by Sunyingbin** [comment]
第一次有报错，我又重新make all了一下，会不会有影响

**Comment by Sunyingbin** [comment]
我再试一下

**Comment by Sunyingbin** [comment]
重新make all了之后是成功的，重新docker-compose up -d还是报之前的错误，我上网查了一下，好像是跟文件格式有关系

**Comment by JackLCL** [comment]
你make all成功之后，你用docler images看看前端docker的镜像能够看到吗?
