### ISSUE TITLE
Image search 2.0 version, how to check the service startup problem

### ISSUE THREAD

**Issue by small-bicycle** [milvus-io/bootcamp#433]
环境： 腾讯云服务器 centos8 系统  python3.6.8版本

按照官网 milvus1.0 和 客户端 服务  使用docker部署完成并成功
![image](https://user-images.githubusercontent.com/51921319/115377057-d52b8c00-a201-11eb-8815-7ad35327bfbc.png)

查询服务 按照教程安装模块并启动 (第三方模块的一些版本好像不是很匹配)
![image](https://user-images.githubusercontent.com/51921319/115377942-a8c43f80-a202-11eb-9561-7fcdc3131dfd.png)

但还是连接不上客户端

**Comment by jingkl** [comment]
You may have to change some dependencies for your own machine

**Comment by small-bicycle** [comment]
更换了模块版本后不报错了，启动后一直这样没反应
![image](https://user-images.githubusercontent.com/51921319/115383288-37878b00-a208-11eb-90f1-3cbf9a133373.png)

请问 关于查询服务这一块有没有详细的教程，比如 模块之间的一些版本对应 或 一些需要主要的坑

**Comment by jingkl** [comment]
The dependencies in this demo have not been tested in detail and can only be solved for problems

**Comment by small-bicycle** [comment]
您好 ， 查询服务器 源码中文件 上传少了 ， 麻烦您看一下
![image](https://user-images.githubusercontent.com/51921319/115836411-08f8f280-a44a-11eb-9eeb-9bdfd8a5c2e0.png)
![image](https://user-images.githubusercontent.com/51921319/115836462-1910d200-a44a-11eb-8b0d-4c127583e604.png)

**Comment by jingkl** [comment]
Here you need to go to image_search_v2/webserver/src/yolov3_detector/data/ path and run the paprepare_model.sh script.

**Comment by small-bicycle** [comment]
您好  图片未能加载成功  程序运行在3 的这个代码块时   报错了 找不到原因
![image](https://user-images.githubusercontent.com/51921319/115859371-afe98880-a462-11eb-8b7a-0bf2cd3e5a33.png)
![image](https://user-images.githubusercontent.com/51921319/115859385-b24be280-a462-11eb-8eb1-171c6d6af3a8.png)

**Comment by jingkl** [comment]
Can I ask you the version of Milvus and pymilvus

**Comment by small-bicycle** [comment]
MIlvus: 1.0 
pymilvus： 1.0.1
是按照这个教程下载安装的：https://github.com/milvus-io/bootcamp/tree/master/solutions/image_search2

**Comment by jingkl** [comment]
Can you type out the version to see it, or look at that part import NoneType this

**Comment by emmataobao** [comment]
你好你的上传问题解决了吗？我上传的时候报错

**Comment by jingkl** [comment]
> 你好你的上传问题解决了吗？我上传的时候报错
What is the problem reported

**Comment by shiyu22** [comment]
not activate, closed.
