### ISSUE TITLE
Connect server failed when I python3 app.py

### ISSUE THREAD

**Issue by YY2460767682** [milvus-io/bootcamp#442]
I am attempt to open localhost:8001,but Page error:Error with 'NoneType' object has no attribute 'count_entities' images in this set.
And terminal error:Retry to connect server 192.168.2.242:19512 failed.get table rows: milvus_183......
I don't know where it's wrong?

**Comment by JackLCL** [comment]
Which demo are you building?

**Comment by YY2460767682** [comment]
> Which demo are you building?

Reverse Image Search Based on Milvus （v2.0）

**Comment by jingkl** [comment]
Milvus version and  pymilvus version Inconsistency
