### ISSUE TITLE
以图搜图，milvus:1.0.0、 pic-search-webserver:1.0、pic-search-webclient:1.0版本，连接milvus超时，但用python脚本可以连接

### ISSUE THREAD

**Issue by lizheng0329** [milvus-io/bootcamp#443]
以图搜图，milvus:1.0.0、 pic-search-webserver:1.0、pic-search-webclient:1.0版本，连接milvus超时，但用python脚本可以连接。搭建完全按照  https://github.com/milvus-io/bootcamp/blob/master/solutions/pic_search/README.md 搭建。pic-search-webserver docker 的内部app.log 的日志文件显示Fail connecting to server on  xx.xx.xx.xx:19530. Timeout,  'NoneType' object has no attribute 'count_entities'

**Comment by JackLCL** [comment]
你在webserver容器的内部使用python客户端看看能连接容器外面的milvus吗？ 另外，你启动webserver容器使用的milvus ip是什么？注意不要使用127.0.0.1

**Comment by JackLCL** [comment]
如果你还有其他关于milvus使用的问题，欢迎加入我们的技术交流群：
![image](https://user-images.githubusercontent.com/53512883/117251990-f504b600-ae77-11eb-8f67-01a18f3620f8.png)

**Comment by OysterQAQ** [comment]
> 如果你还有其他关于milvus使用的问题，欢迎加入我们的技术交流群：
> ![image](https://user-images.githubusercontent.com/53512883/117251990-f504b600-ae77-11eb-8f67-01a18f3620f8.png)
能再发一下企业微信二维码么

**Comment by JackLCL** [comment]
![image](https://user-images.githubusercontent.com/53512883/118345247-bd77c700-b565-11eb-9454-e8e313e3fb94.png)
