### ISSUE TITLE
ImportError: cannot import name 'DataType'

### ISSUE THREAD

**Issue by HoangTienDuc** [milvus-io/bootcamp#458]
i tried to create collection with milvus 1.1.0
```
import collections
from milvus import Milvus, DataType
from common.config import MILVUS_HOST, MILVUS_PORT, TOP_K


milvus = Milvus(host=MILVUS_HOST, port=MILVUS_PORT)

def create_table(client, table_name, dimension):
    collection_param = {
    "fields": [
        {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": dimension}},
    ],
    "segment_row_limit": 800000,
    "auto_id": True
    }
    try:
        status = client.create_collection(table_name, collection_param)
        return status
    except Exception as e:
        print("Milvus ERROR:", e)

create_table(milvus, 'test_db', 512)
```
but it is failed
```
Traceback (most recent call last):
  File "tmp.py", line 2, in <module>
    from milvus import Milvus, DataType
ImportError: cannot import name 'DataType
```

**Comment by JackLCL** [comment]
Do you have the corresponding version of pymilvus installed?

**Comment by HoangTienDuc** [comment]
Yes. My pymilvus == 1.1.0

**Comment by JackLCL** [comment]
https://github.com/milvus-io/pymilvus/blob/v1.1.0/examples/example.py
Please refer this example.

**Comment by HoangTienDuc** [comment]
Hello, thank for your response. I run example successfully. but i cannot:
- Create_collection with DataType.FLOAT_VECTOR if using ver 1.0.0
```
Traceback (most recent call last):
  File "tmp.py", line 21, in <module>
    create_table(milvus, 'test_db', 512)
  File "tmp.py", line 10, in create_table
    {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": dimension}},
  File "/home/tienduchoang/miniconda3/envs/tf1/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: FLOAT_VECTOR
```
- Cannot import name 'DataType if using ver 1.1.0

**Comment by shiyu22** [comment]
Hi, DataType is indeed not supported in pymilvus 1.1, please refer to the [corresponding version](https://milvus.io/docs/v1.1.0/overview.md) of the tutorial on [creating collections](https://milvus.io/docs/v1.1.0/create_drop_collection_python.md).

**Comment by shiyu22** [comment]
Hi, DataType is indeed not supported in pymilvus 1.1, please refer to the [corresponding version](https://milvus.io/docs/v1.1.0/overview.md) of the tutorial on [creating collections](https://milvus.io/docs/v1.1.0/create_drop_collection_python.md).

**Comment by shiyu22** [comment]
not activate, closed.
