### ISSUE TITLE
After the image search 2.0 is built, an error occurs when the server is requested, please advice

### ISSUE THREAD

**Issue by jnyk** [milvus-io/bootcamp#465]
以图搜图2.0搭建完成后,当client向server发送请求时server报错并退出进程
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621581499 (unix time) try "date -d @1621581499" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x45) received by PID 18720 (TID 0x7fcb91579700) from PID 69 ***]

Segmentation fault (core dumped)

经过搜索好像这个错误好像是paddlepaddle模块报出的错误，但是不知道怎么解决，求各位帮助

**Comment by jingkl** [comment]
Sorry, we have not had similar problems so far
Some online references are given here.
1. conda install nomkl
2. Test if paddle is installed successfully
import paddle.fluid
paddle.fluid.install_check.run_check()
3. change version python version greater than 3.7.4
4. cudnn downgrade to 7.6.5

**Comment by jnyk** [comment]
谢谢你的回复，对了我的电脑没有独立显卡，所以没有使用cudnn ，请问是否可能和这有关

**Comment by jingkl** [comment]
Yes, there is a high probability

> 谢谢你的回复，对了我的电脑没有独立显卡，所以没有使用cudnn ，请问是否可能和这有关

**Comment by jnyk** [comment]
哦明白了，接下来我需要先找一台有独立显卡的电脑

**Comment by jingkl** [comment]
You can try running Image Search version 1.0 if you don't have a strong need for target detection. https://github.com/milvus-io/bootcamp/blob/1.0/solutions/pic_search/README.md

**Comment by shiyu22** [comment]
not activate, closed.
