### ISSUE TITLE
What is the table structure of the database when building Textsys?

### ISSUE THREAD

**Issue by jnyk** [milvus-io/bootcamp#466]
在尝试搭建Textsys时，执行python main.py --collection test11 --title data/title.txt --version data/version.txt --load
一直没有反应，怀疑是因为没有对应的数据库，所以自己添加了配置文件中对应的testdb库，再次执行，还是一直卡住没反应，查看数据库发现数据表也一直没有生成，请问是不是需要先自己建表，表结构是怎么样的呢？

**Comment by jingkl** [comment]
Consider the following aspects.
1. is the need to create tables in accordance with the config file
2. you have successfully installed postgres, postgres needs to give user rights
3. Consider that if the docker start postgres may not be replicated successfully
4. table structure is id, questions, answers

**Comment by jnyk** [comment]
感谢回复
1.Textsys是跟着bootcamp中的Textsys readme教程搭建，所以没有配置文件来创建表
2.已经成功安装 postgres 并且已经成功授权，通过其他局域网中的数据库操作软件能够连接并检索数据
3.postgres 是通过apt-get install 安装的，不是用的docker启动
4.请问一下这个表结构中 id字段是什么数据格式啊，数字还是字符串呢

**Comment by jingkl** [comment]
Can you link to postgres and execute this copy of the sql statement?
Id is the int type, numeric form

**Comment by shiyu22** [comment]
not activate, closed.
