### ISSUE TITLE
milvus

### ISSUE THREAD

**Issue by Devictor0815** [milvus-io/bootcamp#475]
以图搜图，milvus:1.0.0、 pic-search-webserver:1.0、pic-search-webclient:1.0版本，启动docker之后无异常，但是前段页面无法打开，日志文件无报错但是在无任何操作的情况下log文件无限被写入sql

**Comment by Devictor0815** [comment]
![image](https://user-images.githubusercontent.com/44083603/119302801-4ba32a00-bc97-11eb-9e5c-de14d3749e2e.png)
![image](https://user-images.githubusercontent.com/44083603/119302826-56f65580-bc97-11eb-8840-d47362eeb638.png)

**Comment by shiyu22** [comment]
The log in screenshot is printed every second by Milvus service, which is normal. 

As for the port is inaccessible, it should be a network problem, you can check the network firewall and [other issues](https://blog.csdn.net/qq_28898309/article/details/108703388).
