### ISSUE TITLE
Can't connect to pic-search-webserver Container : 404 not found error

### ISSUE THREAD

**Issue by EUCHI1996** [milvus-io/bootcamp#477]
hello ,

I created the 3 containers ( milvus, webserver and webclient), and when i try to test the connection to the pic-search-webserver container with the command curl localhost:35000 i got this issue :

##################
![webserver-error](https://user-images.githubusercontent.com/57757186/119575249-06761980-bdb7-11eb-886e-0976ce90343d.PNG)
#######################
this is the logs of the container :
![webserver-logs](https://user-images.githubusercontent.com/57757186/119575271-1130ae80-bdb7-11eb-9454-81c04516db0e.PNG)

#######################
this is the running containers :

![running-containers](https://user-images.githubusercontent.com/57757186/119575390-4937f180-bdb7-11eb-8201-71415f2905e5.PNG)

**Comment by shiyu22** [comment]
Hi, it looks normal from docker log, if you want to use it via curl, you are supposed to set the interface according to the code, please refer to [app.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/image_similarity_search/quick_deploy/server/src/app.py), for example, you need to run `curl localhost:35000/api/v1/count`, note the method is POST.

One more question, can you open the website with 127.0.0.1:8001 in your browser for search?

**Comment by EUCHI1996** [comment]
Hello,
Yes, i deployed the webclient and it works fine on localhost:8001 but when i try to load data and i put the /tmp/pic1 path  on the wabclient it does not work. So, i try to connect to the webserver using curl command (cur localhost:35000), it does not work it give me 404 not found

**Comment by EUCHI1996** [comment]
Can any one help me to resolve this issue please ????

**Comment by shiyu22** [comment]
Please note the version of Milvus and webserver.

Are there any errors reported in your browser? Also, you can check the status of network requests in your browser: right-click and select check ->network.

And you can check the commend of start docker. Or can you show the commend to start Milvus and the webserver?

**Comment by EUCHI1996** [comment]
Hello,

For the milvus i used this image (milvusdb/milvus:1.1.0-cpu-d050721-5e559c), webserver (milvusbootcamp/pic-search-webserver:1.0) and for the webclient (milvusbootcamp/pic-search-webclient:1.0).
No, i don't have any error on the browser, the webclient works fine on port 8001 but when i put the path /tmp/pic1 it don't load images from the webserver.

################### Command to start Milvus container ###########

docker run -d --name milvus_cpu_1.0.0  \
-p 19530:19530 \
-p 19121:19121 \
-v /home/$USER/milvus/db:/var/lib/milvus/db \
-v /home/$USER/milvus/conf:/var/lib/milvus/conf \
-v /home/$USER/milvus/logs:/var/lib/milvus/logs \
-v /home/$USER/milvus/wal:/var/lib/milvus/wal \
milvusdb/milvus:1.1.0-cpu-d050721-5e559c

################## command to start the webserver container ##################
docker run -d --name zilliz_search_images_demo \
-v ${IMAGE_PATH1}:/tmp/pic1 \   # IMAGE_PATH1 : reference to the path where iamges are stored in my local machine.
-p 35000:5000 \
-e "MILVUS_HOST=172.16.0.4" \  # 172.16.0.4 : the ip address for the docker host where running milvus.
milvusbootcamp/pic-search-webserver:1.0

############## command tio start webclient ###################
docker run -d --rm --name zilliz_search_images_demo_web  \
 -p 8001:80
-e API_URL=http://172.16.0.4:35000 \
milvusbootcamp/pic-search-webclient:1.0

**Comment by EUCHI1996** [comment]
when i try to connect to the webserver container using this command  : curl -X POST localhost:35000/api/v1/train
 i get on issue : Error with [Errno 2] No such file or directory: '/data/jpegimages' ??

**Comment by shiyu22** [comment]
The command to run docker looks fine and I have re-run it on my own machine with no problems. 
Have you modified the source code? You can troubleshoot the problem in several ways:
1. Make sure Milvus started and you can run the [example code](https://milvus.io/docs/v1.1.0/example_code.md) successfully.
2. You can run `docker logs+<container id>` to check the logs of each container and note the logs of the webserver.
3. For the webserver log, you can also use the commend `docker exec -ti +<container id> bash` to get into the container, then to get the contents of **app.log**.

**Comment by EUCHI1996** [comment]
Hello,

1. Milvus Works Fine, i tested the example code.
#######################
2. .1 Milvus Logs:
![image](https://user-images.githubusercontent.com/57757186/120380880-08ddf380-c322-11eb-8d20-a2afec611be0.png)
2..2 pic-searchwebserver logs.
![image](https://user-images.githubusercontent.com/57757186/120381009-33c84780-c322-11eb-9647-aa3e1646bd1d.png)
################################
3. app.log contains  : 

![image](https://user-images.githubusercontent.com/57757186/120381123-55293380-c322-11eb-98fc-35f3a9a528c3.png)

**Comment by shiyu22** [comment]
In the app.log, an error is reported that the version does not matched, according to [this tutorial](https://github.com/milvus-io/bootcamp/tree/master/solutions/image_similarity_search/quick_deploy), you are supposed to [install Milvus 1.0](https://milvus.io/docs/v1.0.0/milvus_docker-cpu.md) instead of Milvus 1.1.

**Comment by EUCHI1996** [comment]
Yes, i installed the expected version, and i still have the same error. I thnik that the error in the app.py code.
Are you available for a remote session please, because it's urgent i need to use Milvus in our project .

**Comment by shiyu22** [comment]
Yes, you can join our [slack channel](https://join.slack.com/t/milvusio/shared_invite/zt-e0u4qu3k-bI2GDNys3ZqX1YCJ9OM~GQ).

**Comment by shiyu22** [comment]
not activate, closed.
