### ISSUE TITLE
以图搜图测试程序搭建完成上传报错

### ISSUE THREAD

**Issue by emmataobao** [milvus-io/bootcamp#478]
Error with 'NoneType' object has no attribute 'count_entities' images in this set
上传图片路径点击然后报错。

**Comment by shiyu22** [comment]
Please note the version of Milvus and webserver. So which version of Milvus and webserver are you use?

**Comment by emmataobao** [comment]
谢谢， 版本更换之后上传错误不在，但是我文件夹只有2 张图片 ，但是 出现 4 images in this set。 我用原图进行上传搜索无反应
![Uploading image.png…]()

**Comment by emmataobao** [comment]
谢谢， 版本更换之后上传错误不在，但是我文件夹只有2 张图片 ，但是 出现 4 images in this set。 我用原图进行上传搜索无反应
![1622447948(1)](https://user-images.githubusercontent.com/46233536/120161221-a6a1c780-c229-11eb-9031-b72e25a72f7e.png)

**Comment by shiyu22** [comment]
Are you using object detection? If it is object detection, the data will be saved according to the number of objects in the image.

But I think you are multiple loads, which means you clicked `+` once before, so there is one more copy of the data. You can delete the data in Milvus, delete the webserver docker and restart it again, so you can make sure the data is cleared.

**Comment by emmataobao** [comment]
谢谢你的回复，我查了好像是一个接口的问题http://localhost:5000/api/serach 好像不能使用，但不知道该怎么解决
![1622452780(1)](https://user-images.githubusercontent.com/46233536/120171689-e3bf8700-c234-11eb-84ef-525e5211a0cb.png)

**Comment by shiyu22** [comment]
So what is the logs of the docker?

**Comment by emmataobao** [comment]
谢谢你，问题已经解决。搜索问题已经解决，非常感谢你的帮助

**Comment by Zhouchuanwen** [comment]
> 谢谢你，问题已经解决。搜索问题已经解决，非常感谢你的帮助

怎么解决的，我也遇到了

**Comment by xiaohui0225** [comment]
> 谢谢，版本替换上传错误不在，但是我文件夹之后只有2张图片，但是在这组图片中出现了4张图片。 我用原图进行上传搜索无反应 ![1622447948(1)](https://user-images.githubusercontent.com/46233536/120161221-a6a1c780-c229-11eb-9031-b72e25a72f7e.png)

请问最初的这个问题你是怎么解决的呢？我试了最新版也不可以，我的系统是在虚拟机上的ubuntu22.04.
