### ISSUE TITLE
.env: file does not exist

### ISSUE THREAD

**Issue by 17853100899** [milvus-io/bootcamp#487]
Building a video search system based on Milvus

cd search-video-demo & make all
...
Step 14/17 : COPY .env .
COPY failed: file not found in build context or excluded by .dockerignore: stat .env: file does not exist

Where is the .env file

**Comment by JackLCL** [comment]
I have uploaded .env file. You can try again.

**Comment by shiyu22** [comment]
not activate, closed.

**Comment by shiyu22** [comment]
not activate, closed.
