### ISSUE TITLE
pip3 install module incompatible，can you update the version list，what`s version  python you  used?

### ISSUE THREAD

**Issue by lxy826076** [milvus-io/bootcamp#489]
i want to run the demo on my computer not use docker，but some module version error

**Comment by shiyu22** [comment]
Which solution do you want to run? And the base docker you can find in Dockerfile and get the relevant python version.

**Comment by lxy826076** [comment]
run search picture 2.0，i used the dockerfile commond but have version  conflict，is the docker of tensorflow/tensorflow version cause it?

**Comment by miia12** [comment]
Can you upload the screenshot of the error?

**Comment by miia12** [comment]
We used python 3.8. And can you upload the screenshot of the error?

**Comment by miia12** [comment]
Thanks for your advice. We'll make the versions consistent.

**Comment by miia12** [comment]
Where do you see the version of tensorflow 1.x? We have removed the tensorflow in requirements.txt.

**Comment by lxy826076** [comment]
from dockerfile

**Comment by shiyu22** [comment]
not activate, closed.
