### ISSUE TITLE
QA system, cannot see anything on the front end

### ISSUE THREAD

**Issue by deep-practice** [milvus-io/bootcamp#490]
服务部署好之后，访问 http://ip:8000/docs 可以看到浏览器标题显示FastAPI-Swagger UI，但是界面为空白。

**Comment by deep-practice** [comment]
NFO:     Started server process [4375]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://192.168.10.154:8000 (Press CTRL+C to quit)
INFO:     10.205.48.10:48914 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.205.48.10:57005 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.205.48.10:47914 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.205.48.10:56925 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.205.48.10:44611 - "GET /docs HTTP/1.1" 200 OK

**Comment by shiyu22** [comment]
Maybe you need to type http://192.168.10.154:8000/docs in your browser.

**Comment by deep-practice** [comment]
That's  exactly what I did.I only saw the title 'FastAPI-Swagger UI',no content provided.

**Comment by Bennu-Li** [comment]
What is the version of your fastapi？
Maybe you can reference these docs to try: 
https://blog.csdn.net/qq_44683653/article/details/107542463
https://blog.csdn.net/weixin_43632687/article/details/110419982

**Comment by shiyu22** [comment]
not activate, closed.
