### ISSUE TITLE
python milvus connection pool

### ISSUE THREAD

**Issue by lxy826076** [milvus-io/bootcamp#494]
i can`t find some infmation about conn pool at milvus official website,can i customize connection size，should i close the connetion every time?

**Comment by Bennu-Li** [comment]
You don't need to close the connection every time. And currently Milvus does not support custom connection pool sizes, the default number of connection pools is 10. If you want to custom connection the pool size, please send us an issue on Milvus Github: https://github.com/milvus-io/milvus/issues

**Comment by shiyu22** [comment]
not activate, closed.
