### ISSUE TITLE
reversed_image_search ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by loveljy119** [milvus-io/bootcamp#500]
![image](https://user-images.githubusercontent.com/863935/122658814-3c36d400-d1a4-11eb-94ff-d41631990567.png)

如上图，这种情况是数据导入重复导致的吗？

**Comment by shiyu22** [comment]
Have you modified the source code? It looks like there is a problem with the code somewhere. You can also go into docker and look at the app.log information.

**Comment by loveljy119** [comment]
没有修改过源码 图上的日志就是webserver app.log的日志

**Comment by miia12** [comment]
你可以尝试一下我们最新的以图搜图镜像么？

**Comment by shiyu22** [comment]
not activate, closed.
