### ISSUE TITLE
cannot find the source of img.npy in the readme of the Tag1.0 ctirg project 

### ISSUE THREAD

**Issue by cumt10105** [milvus-io/bootcamp#501]
https://github.com/milvus-io/bootcamp/tree/1.0/solutions/ctirg
如题，Tag 1.0 solutions中ctirg项目， readme中关于导入数据的说明，
无法找到img.npy的出处说明，请告知生成img.npy的制作办法。
![image](https://user-images.githubusercontent.com/43465077/122674576-560a0280-d208-11eb-8ed1-a58c8b7b6e51.png)

**Comment by jingkl** [comment]
The data in this project is exported from the thesis source code, please see the thesis source code if needed

**Comment by cumt10105** [comment]
> The data in this project is exported from the thesis source code, please see the thesis source code if needed

do you mean in this project https://github.com/google/tirg.git?

**Comment by shiyu22** [comment]
not activate, closed.
