### ISSUE TITLE
MolSearch，extracting feature stopped at 9929

### ISSUE THREAD

**Issue by zillionare** [milvus-io/bootcamp#520]
env:
server image: milvusbootcamp/mols-search-webserver:0.7.0
client image: milvusbootcamp/mols-search-webclient:0.3.0 

test data:
[test_1w.smi](https://github.com/milvus-io/bootcamp/blob/master/solutions/molecular_similarity_search/smiles-data/test_1w.smi)

error logs:

extracting feature from smi No. 9928 , 10000 molecular in total
extracting feature from smi No. 9929 , 10000 molecular in total
Retry to connect server 192.168.110.236:19530 failed.
Retry to connect server 192.168.110.236:19530 failed.

if I use test_100.smi, it works.

**Comment by shiyu22** [comment]
It looks like Milvus was disconnected during the insertion process. Please make sure that Milvus starts successfully and that you can run [example.py](https://github.com/milvus-io/pymilvus/blob/master/examples/example.py), but of course, you have to note the version of Milvus.

Also, it is recommended that you use version 1.1: https://github.com/milvus-io/bootcamp/tree/1.1/solutions/molecular_similarity_search/quick_deploy

**Comment by shiyu22** [comment]
not activate, closed.
