### ISSUE TITLE
cannot connect to reverse_image_search

### ISSUE THREAD

**Issue by loveljy119** [milvus-io/bootcamp#521]
reverse_image_search服务器长时间不连接，再次连接报错
![image](https://user-images.githubusercontent.com/863935/123428334-4586cd00-d5f8-11eb-8112-e023b8a134ca.png)

**Comment by shiyu22** [comment]
Thanks, this is a really good question, it is caused by long Pymysql connections and can be solved by `mysql.ping()`.
```python
def test_connection():
    try:
	db.ping()
    except:
	db = pymysql.connect(localhost, user, passwd, port, db)
    return db
```
And we will fix&update it later.
