### ISSUE TITLE
以图搜图object_detection的requirements.txt中starlette包冲突

### ISSUE THREAD

**Issue by BeBraveBeCurious** [milvus-io/bootcamp#522]
希望能测试之后，把文件中的版本更改为`starlette==0.14.2`

![image](https://user-images.githubusercontent.com/42266336/123615821-3db56b80-d838-11eb-9254-369255b1c77c.png)

**Comment by miia12** [comment]
We noticed this error. But as it didn’t cause problems, we didn’t re-dockerlize the project. Maybe we will replace the version in the next upgrade. Thx

**Comment by miia12** [comment]
Upgrades images
