### ISSUE TITLE
 The image path in fastapi after starting to search for images has an error, and an error is reported **path is not a file** 

### ISSUE THREAD

**Issue by BeBraveBeCurious** [milvus-io/bootcamp#523]
在第一个api `image_path`里输入服务器上有jpg图片的绝对路径后
![image](https://user-images.githubusercontent.com/42266336/123616279-b9afb380-d838-11eb-8494-7d868fb761c8.png)

后台返回输入的**路径 is not a file**。

![image](https://user-images.githubusercontent.com/42266336/123616801-38a4ec00-d839-11eb-8f7b-74bc0ef1f996.png)

**Comment by miia12** [comment]
Try to replace a folder path, or write a python script to check whether it works. Thx

**Comment by BeBraveBeCurious** [comment]
I have searched [FileResponse in FastAPI](https://fastapi.tiangolo.com/zh/advanced/custom-response/?h=filer#fileresponse). The related code is shown as follows:
``` python3
from fastapi import FastAPI
from fastapi.responses import FileResponse

some_file_path = "large-video-file.mp4"
app = FastAPI()

@app.get("/")
async def main():

    return FileResponse(some_file_path)
```
In this example, I guess that a folder path is not allowed as the input of file_path or image_path. The input information should be a file with file extensions, such as jpg, png in the reverse image search project.

**Comment by shiyu22** [comment]
not activate, closed.
