### ISSUE TITLE
Unable to run Reverse Image Search Demo on my machine

### ISSUE THREAD

**Issue by jielinxu** [milvus-io/bootcamp#54]
I successfully built the demo system following https://github.com/milvus-io/bootcamp/blob/master/demo/pic_search/README.md, however, loading images into Mivus failed.

My machine details:
Graphics: GeForce MX150/PCIe/SSE2
Processor: Intel Core i7-8550U CPU @1.80GHz * 8

**Comment by jielinxu** [comment]
I tried again and it succeeded. BTW, it seemed that .jpeg image was not loaded into Milvus. It would be helpful if supported image format is listed.

**Comment by JackLCL** [comment]
Thanks, I will add this to the article.
