### ISSUE TITLE
Cannot run main.py -> No module named 'uvicorn'

### ISSUE THREAD

**Issue by joaocps** [milvus-io/bootcamp#549]
![uvicorn](https://user-images.githubusercontent.com/23501993/125486005-fd931313-c4bd-49dd-85f0-008edc38ab14.JPG)

Docker containers runing and requirements.txt installed.

No module named 'uvicorn' error persists, any solution for this?
I'm following -> https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy Tutorial.

**Comment by jingkl** [comment]
You can try pip3 install uvicorn

**Comment by joaocps** [comment]
@jingkl Solved!

Another questions:
- When i load more images i increment the dataset size or I replace the older dataset with the new one?
- Is it not possible to search on images greater than 3mb?
- Finally, is it possible after performing the similarity search in the dataset that I introduce the image I searched in the dataset?

**Comment by jingkl** [comment]
1.increment the dataset size
2.It should work, but it will be slow
3.Yes, you can.

**Comment by joaocps** [comment]
@jingkl Thank you very much ! U rock !
Is there any way to use gpu in the feature extraction process? Wouldn't it speed up the extraction process?

**Comment by jingkl** [comment]
If gpu is used in feature extraction, it will speed up the extraction of features
