### ISSUE TITLE
The user's banner and banner color appear to only be returned on the canary API currently, and only a small percentage of users can set their banner color.

### ISSUE THREAD

**Issue by chole22** [milvus-io/bootcamp#553]
The user's banner and banner color appear to only be returned on the canary API currently, and only a small percentage of users can set their banner color.

_Publicación original de @RedDaedalus en https://github.com/discord/discord-api-docs/pull/3448_

**Comment by chole22** [comment]
#6557

**Comment by shiyu22** [comment]
We cannot catch you.
