### ISSUE TITLE
connections.connect(host='localhost', port='19537') ，timeout

### ISSUE THREAD

**Issue by xianghuisun** [milvus-io/bootcamp#556]
There seems to be a problem with this port. 
docker-compose ps. The port shown in this command is 19530.
The port number 19537 needs to be replaced.

**Comment by jingkl** [comment]
Can you tell me which bootcamp it is, and better give a connection?

**Comment by xianghuisun** [comment]
https://github.com/milvus-io/bootcamp/blob/master/solutions/question_answering_system/question_answering.ipynb

connections.connect(host='localhost', port='19537')
The port number 19537 needs to be replaced by 19530 if docker-compose command show 19530

**Comment by jingkl** [comment]
Modified, thanks

**Comment by xianghuisun** [comment]
https://github.com/milvus-io/bootcamp/blob/master/solutions/question_answering_system/question_answering.ipynb




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/bootcamp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/bootcamp] connections.connect(host='localhost', port='19537') ，timeout (#556)





 
Can you tell me which bootcamp it is, and better give a connection?
