### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by laol777** [milvus-io/bootcamp#560]
I have huge ram memory allocation for [100 M test](https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md) on Milvus 2.0
after the end of the test, I have 80 GB of memory allocated.

steps to reproduce the problem:

1. **(start standalone milvus)** [installation link](https://milvus.io/docs/install_standalone-docker.md)
``` 
wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
docker-compose up -d
```
2. **(run test)**
make test by instruction https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab2_sift1b_100m.md#2-create-a-table

**Comment by Bennu-Li** [comment]
We'll try to reproduce this problem later.

**Comment by shiyu22** [comment]
@laol777 Maybe you have the same issue about [#7049](https://github.com/milvus-io/milvus/issues/7049), you can follow it.

**Comment by shiyu22** [comment]
not activate.
