### ISSUE TITLE
Error when trying to deploy reversed image search

### ISSUE THREAD

**Issue by Ooooooooooooooooooooqp** [milvus-io/bootcamp#565]
ubantu18.04
首先安装python环境pymilvus==1.0.1找不到
root@wlw-HP-Z840-Workstation:/home/wlw/bootcamp-1.0/solutions/image_search2/webserver# pip install pymilvus
Collecting pymilvus
  Could not find a version that satisfies the requirement pymilvus (from versions: )
No matching distribution found for pymilvus

然后运行python app.py
root@wlw-HP-Z840-Workstation:/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src# python app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from service.train import do_train
  File "/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src/service/train.py", line 79
    return print("train finished")
请问这是什么问题？

**Comment by jingkl** [comment]
Please use Milvus 2.0' version  image search

**Comment by Ooooooooooooooooooooqp** [comment]
ok 我试试

**Comment by Ooooooooooooooooooooqp** [comment]
不是吧，我是参考官方搭建方案啊：
![image](https://user-images.githubusercontent.com/86219920/127255247-46b505f5-312e-4962-961b-53f11be9a740.png)

你说的版本应该怎么搭建？
我需要的这个功能有没有？
![image](https://user-images.githubusercontent.com/86219920/127255384-751d16ac-c842-4a79-bbba-73c832d96287.png)

**Comment by Ooooooooooooooooooooqp** [comment]
不行，换了Milvus2.0还是一样的报错

**Comment by Ooooooooooooooooooooqp** [comment]
使用pip3 install -r requirements.txt装完环境了，但是运行app.py依然报错
root@wlw-HP-Z840-Workstation:/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src# python app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from service.train import do_train
  File "/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src/service/train.py", line 79
    return print("train finished")
SyntaxError: invalid syntax

root@wlw-HP-Z840-Workstation:/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src# python3 app.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from service.train import do_train
  File "/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src/service/train.py", line 9, in <module>
    from yolov3_detector.paddle_yolo import run, YOLO_v3 as Detector
  File "/home/wlw/bootcamp-1.0/solutions/image_search2/webserver/src/yolov3_detector/paddle_yolo.py", line 10, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.6/dist-packages/paddle/__init__.py", line 45, in <module>
    import paddle.distributed  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/__init__.py", line 15, in <module>
    from .spawn import spawn  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/spawn.py", line 28, in <module>
    from paddle.distributed.fleet.cloud_utils import use_paddlecloud
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/__init__.py", line 20, in <module>
    from .base.fleet_base import Fleet  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/base/fleet_base.py", line 32, in <module>
    from ..meta_parallel import TensorParallel, model_parallel_random_seed
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/meta_parallel/__init__.py", line 15, in <module>
    from .parallel_layers import VocabParallelEmbedding  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/meta_parallel/parallel_layers/__init__.py", line 15, in <module>
    from .mp_layers import VocabParallelEmbedding  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/meta_parallel/parallel_layers/mp_layers.py", line 18, in <module>
    from paddle.nn import functional as F
  File "/usr/local/lib/python3.6/dist-packages/paddle/nn/__init__.py", line 23, in <module>
    from .layer.activation import ELU  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/nn/layer/__init__.py", line 19, in <module>
    from . import container  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/nn/layer/container.py", line 17, in <module>
    from six.moves import collections_abc
ImportError: cannot import name 'collections_abc'

**Comment by Ooooooooooooooooooooqp** [comment]
救命啊~~~~~
求救~~~~

**Comment by jingkl** [comment]
https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search 
你用这个吧，代码已经升级了，看bootcamp的教程https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/object_detection

**Comment by Ooooooooooooooooooooqp** [comment]
按照楼上给的链接，尝试搭建新的object_detection with yolo3.
第一步搭建好milvus。
第二步
![image](https://user-images.githubusercontent.com/86219920/127976886-69e8417d-fa14-4376-a847-30e6eb2e7bcb.png)
请问这里的docker是要自己建么？
![image](https://user-images.githubusercontent.com/86219920/127977164-7f9da211-cab2-4f1f-a6f3-6a70c83595cb.png)
但是Dockerfile的路径怎么是/app/
请问该如何处理？

**Comment by shiyu22** [comment]
This image `milvusbootcamp/imgsearch-with-objdet:2.0` exists in Dockerhub, and you can download it by yourself.

If you want to build the image by yourself, you can use `docker build -t <image name> .` with the Dockerfile.

**Comment by Ooooooooooooooooooooqp** [comment]
谢谢，我试试

**Comment by Ooooooooooooooooooooqp** [comment]
依照搭建手册操作
![image](https://user-images.githubusercontent.com/86219920/128276810-d4ba90f6-731f-4c36-9c75-982c7bd1ca59.png)
但是却报错
![image](https://user-images.githubusercontent.com/86219920/128276846-be8801c9-3086-4eaf-a8d9-13d223abf498.png)
是何原因请问？

**Comment by Ooooooooooooooooooooqp** [comment]
搭建完成以后，点击+号没反应额。
以下是日志
![1](https://user-images.githubusercontent.com/86219920/128664476-7456656d-11d0-4320-85dd-60c878e43bab.png)
点击fastapi的日志
![2](https://user-images.githubusercontent.com/86219920/128664511-162c32c7-768e-44f4-b9fd-5b398c6d3df3.png)
请问该怎么办？

**Comment by Ooooooooooooooooooooqp** [comment]
半天没人回复我，我就又试了试Run the code。
第一步成功
![image](https://user-images.githubusercontent.com/86219920/128800006-a779538a-7601-49c4-8aad-a36d357947d6.png)
但是Start Client后点+号还是没反应。
而且我发现了一个问题，
![image](https://user-images.githubusercontent.com/86219920/128800291-67b124b3-66bf-4605-8930-d3bbdfdd75fe.png)
这里说是“milvusbootcamp/img-search-server:2.0”
到后面就变成了“pic_search_webserver”
![image](https://user-images.githubusercontent.com/86219920/128800385-ecd8c23e-3a05-4c78-8bba-8732684d48ad.png)
很混乱。
于是我就把各个版本都下下来了
![image](https://user-images.githubusercontent.com/86219920/128800531-4c9f3375-f80b-4793-9241-9400e976d3e2.png)
都有问题，无语。。。

**Comment by Ooooooooooooooooooooqp** [comment]
唯一可以用的一套server和client
![image](https://user-images.githubusercontent.com/86219920/128801492-6218b0e8-ba8e-4cf7-a5d5-42b56406f0a0.png)
![image](https://user-images.githubusercontent.com/86219920/128801526-2e4643c6-a4f9-43c0-9942-dba0670c62a0.png)
但是我想试试目标检测-yolo v3...

**Comment by shiyu22** [comment]
Hundreds of people have successfully deployed the Image Search demo with Milvus 2.0. Please clean your environment and re-deploy the whole project according to the [object-detection tutorial](https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/object_detection). If you run into any errors, first try to troubleshoot in your browser; if there is no luck, please respond to this issue with the error message from the client and more importantly, the log file and configurations of Milvus; it is very challenging to troubleshoot with only the information you are providing.

**Comment by Ooooooooooooooooooooqp** [comment]
Well,I have a problem.
When I use object_detection,the server must be down,and the log is nothing.
![3](https://user-images.githubusercontent.com/86219920/129132730-7fc857d5-3f08-4bbd-8c63-af22c0d587cb.png)

And I can't get the client logs.
So How can I start client Run the code ,not docker?

**Comment by Ooooooooooooooooooooqp** [comment]
Hi,I have a  problem.
The When I click the +,there is nothing changes.
the log is 
![image](https://user-images.githubusercontent.com/86219920/129520810-56243eef-c6be-44c6-a6ea-9147e61381ee.png)

My milvus is 2.0,
Webserver is \bootcamp-master\solutions\reverse_image_search\object_detection,
Client is milvusbootcamp/img-search-client:1.0/

Help me!!!

**Comment by shiyu22** [comment]
I think this is a pymilvus error, do you have pymilvus-orm installed and which version do you have installed? Also, what is the version of Milvus, 2.0.0-rc1 or 2.0.0-rc4? Maybe you need to install the corresponding version.

**Comment by Ooooooooooooooooooooqp** [comment]
Milvus is milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2(docker-compose)
Pymilvus-orm is pymilvus-2.0.0rc4

**Comment by shiyu22** [comment]
That's a bug for Milvus 2.0.0-rc2, you can refer to [this issue](https://github.com/milvus-io/milvus/issues/6989). And the Milvus 2.0.0-rc4 has fixed it, you can reinstall [Milvus:v2.0.0-rc4](https://milvus.io/cn/docs/v2.0.0/install_standalone-docker.md).

**Comment by Ooooooooooooooooooooqp** [comment]
Hi,I have a problem.
I set show top 50 results,but the search results only show 9.
![image](https://user-images.githubusercontent.com/86219920/129670673-eb04ec29-cbcd-4417-8861-06ae7127f183.png)
Please check it for me. TKS

**Comment by shiyu22** [comment]
That's a known feature for object detection. 

First of all, When inserting a picture, object detection is performed on it, for example, if there is a person, a table, and a chair in the picture, then the three objects are stored as three vectors. So the number of images in the system does not match the actual number, there is actually only one image but the interface shows three.

And when searching a picture, the most similar vectors are returned in Milvus, but it is possible that the topk vectors returned correspond to the same picture, but in the final, we will de-weight and sort the returned images, so the result displayed will be less than topk.

**Comment by shiyu22** [comment]
But I see that your screenshot returns 9 same images and it doesn't look like the results are de-duplicated, so are you inserting multiple same images? Or it returns duplicate results, if there is a problem with the results returned then please re-submit a big issue.

**Comment by Ooooooooooooooooooooqp** [comment]
I have hundreds of thousands of pictures to load.
How can I get GPU of TensorFlow?
Next time will be new issue.

**Comment by shiyu22** [comment]
You can follow this issue #183 to use GPU.

**Comment by Ooooooooooooooooooooqp** [comment]
$python3 main.py 

2021-09-27 15:19:50,255 ｜ ERROR ｜ milvus_helpers.py ｜ __init__ ｜ 18 ｜ Failed to connect Milvus: 'Connections' object has no attribute 'connect'

why?
OS Ubuntu 20.04
Milvus is milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2(docker-compose)
Pymilvus-orm is pymilvus-2.0.0rc4
tf 2.6.0

**Comment by shiyu22** [comment]
not activate.
