### ISSUE TITLE
hybrid search wrong link

### ISSUE THREAD

**Issue by digoal** [milvus-io/bootcamp#566]
https://milvus.io/bootcamp
hybrid search链接错误: https://github.com/milvus-io/bootcamp/blob/master/solutions/hybrid_search
![image](https://user-images.githubusercontent.com/1920239/127274490-6e599d6e-2a5a-4849-b831-76fd23ef2596.png)

**Comment by jingkl** [comment]
Hi, this is our Milvus 1.1 version to do a hybird search tutorial
Now milvus 2.0 has been released and already supports  hybird search
I will contact the official website staff to downgrade, thank you for your question

**Comment by shiyu22** [comment]
not activate, closed.
