### ISSUE TITLE
Milvus 2.0 crashes

### ISSUE THREAD

**Issue by Javajava1** [milvus-io/bootcamp#567]
When I was building milvus2.0, after inputting the commands in the official document, it showed 

milvus-etcd...Done,milvus-minio...Done,milvus-standalone...Done,
 but when I started milvusbootcamp/img- When search-server:2.0, the milvus-standalone service will be killed. Check the logs, it shows:
query_coord.go:103] ["query coordinator try to connect etcd failed"] [error="All attempts results:\nattempt #1: Failed to unmarshal message header, err line 5: unknown field name \"source_nodeIDs\" in milvus.proto.common.MsgHeader. 

What is the problem?

**Comment by jingkl** [comment]
For Milvus 2.0 issues, please go to this link (https://github.com/milvus-io/milvus/issues) and ask for the machine configuration, screenshots of the corresponding errors, and log files, please.

**Comment by shiyu22** [comment]
not activate, closed.
