### ISSUE TITLE
Using reversed image search with milvus2.0.0 to search for images, click on the plus sign, no response, no app.log can be found in the webserver docker

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#568]
![image](https://user-images.githubusercontent.com/78945582/127797168-6166bd70-d270-4c78-8135-dfafc2b268b5.png)

![image](https://user-images.githubusercontent.com/78945582/127797126-21cd9fe3-251f-4366-88d7-a841dc3cf0f9.png)

![image](https://user-images.githubusercontent.com/78945582/127797114-85326c2a-8564-4234-98eb-3f54b1520a36.png)

**Comment by shiyu22** [comment]
Can you show the logs with `docker logs + <webserver container id>`, as `docker logs e99a008170cb`. Alternatively, you can check the request information of the network in your browser. It may be that the network is not available and the backend cannot receive the request. So please note that your firewall is turned off and the network is accessible in your browser.

**Comment by lixiangMindSpore** [comment]
> Can you show the logs with `docker logs + <webserver container id>`, as `docker logs e99a008170cb`. Alternatively, you can check the request information of the network in your browser. It may be that the network is not available and the backend cannot receive the request. So please note that your firewall is turned off and the network is accessible in your browser.

防火墙是关的，网络没问题。

**Comment by shiyu22** [comment]
So what's the log with `docker logs`?

**Comment by Ooooooooooooooooooooqp** [comment]
Ihave the same  problem.
when I click +,the log is
![1](https://user-images.githubusercontent.com/86219920/128454629-8a08dee3-fc67-4ef0-bdb2-0fc4b0d3e91d.png)

and when I click FastAPI,the log is 
![2](https://user-images.githubusercontent.com/86219920/128454630-9c95a712-fb1a-49ef-be4b-9aa3fa493c5d.png)

**Comment by shiyu22** [comment]
not activate, closed.
