### ISSUE TITLE
The documentation says to start the container service first, and then run main.py. If you start the container service first, port 5000 will be occupied, and running main.py will cause an error that port 5000 is occupied.

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#570]
![image](https://user-images.githubusercontent.com/78945582/127819414-cfaa35fa-ee43-4356-a50a-f9faca6e20b8.png)

![image](https://user-images.githubusercontent.com/78945582/127819427-3918d177-18c7-488e-9420-c8c2f36cebd8.png)

指导文档
https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy

指导文档里说先启动这个容器服务，然后运行main.py，如果先启动此容器服务，5000端口就被占用了，运行main.py会出现5000端口被占用错误

**Comment by shiyu22** [comment]
You can change the port in [main.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/main.py#L145) before running the code with `python main.py`. For example, you can change it from `5000` to `5001` with `uvicorn.run(app=app, host='0.0.0.0', port=5001)`.

In addition, do you want to modify the [README](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/README.md) file to include a brief guide of how to change the server port?  submit a PR to become a contributor! :)

**Comment by lixiangMindSpore** [comment]
> You can change the port in [main.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/main.py#L145) before running the code with `python main.py`. For example, you can change it from `5000` to `5001` with `uvicorn.run(app=app, host='0.0.0.0', port=5001)`.
> 
> In addition, do you want to modify the [README](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/README.md) file to include a brief guide of how to change the server port? submit a PR to become a contributor! :)

如果把main.py里面的 5000改成5001，会出现如下错误：
![image](https://user-images.githubusercontent.com/78945582/127833571-f6772339-f89b-4cd9-9beb-dcb16dbe9a2e.png)

**Comment by shiyu22** [comment]
Please modify the parameters according to your own environment. Here listing some parameters that need to be set, for more information please refer to [config.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/config.py).

**Comment by shiyu22** [comment]
not activate.
