### ISSUE TITLE
按照指导文档出现如图所示错误该如何解决？

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#571]
指导文档：
https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy

出现问题：
![image](https://user-images.githubusercontent.com/78945582/127821275-59d094f3-5785-46ae-88eb-474cf1e24c27.png)

**Comment by shiyu22** [comment]
This looks like the issue about SQLite and you can find the solution online. Here is a way to change directory permissions that you can refer to:
<img width="753" alt="截屏2021-08-02 15 51 14" src="https://user-images.githubusercontent.com/53459423/127824024-ad6c1513-aa95-4040-998f-7312181007a9.png">

**Comment by lixiangMindSpore** [comment]
> This looks like the issue about SQLite and you can find the solution online. Here is a way to change directory permissions that you can refer to:
> <img alt="截屏2021-08-02 15 51 14" width="753" src="https://user-images.githubusercontent.com/53459423/127824024-ad6c1513-aa95-4040-998f-7312181007a9.png">

这个方法试了，还是不行

**Comment by shiyu22** [comment]
The error is definitely about SQLite, maybe you can try another solution that you have learned online.

BTW, the latest version of reverse image search doesn't use SQLite but MySQL, so what is the issue with your error report? Have you modified the source code?

**Comment by lixiangMindSpore** [comment]
> The error is definitely about SQLite, maybe you can try another solution that you have learned online.
> 
> BTW, the latest version of reverse image search doesn't use SQLite but MySQL, so what is the issue with your error report? Have you modified the source code?

我没改源代码，我也不清楚为啥，按照指导文档走下来就这样了，麻烦您了

**Comment by shiyu22** [comment]
Which version of Milvus are you use?

**Comment by lixiangMindSpore** [comment]
> Which version of Milvus are you use?

2.0.0，已经解决了，的确是权限问题，tmp目录下的权限没打开，谢谢您了
