### ISSUE TITLE
milvus2.0.0，昨天已加载图片成功，今天刷新网页有又显示为0/0，具体如图所示

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#572]
![image](https://user-images.githubusercontent.com/78945582/127940614-46f2b3cd-cf78-43c9-a8a8-ee8b11816831.png)

**Comment by lixiangMindSpore** [comment]
已解决

**Comment by ss892714028** [comment]
> 已解决
Closing this issue since it has been resolved.
