### ISSUE TITLE
milvus2.0.0 is running normally (according to the instruction document), but milvus_img_search cannot be found

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#573]
![image](https://user-images.githubusercontent.com/78945582/127950008-54b7334b-3ab5-43aa-9d2a-36cce8a695cd.png)

![image](https://user-images.githubusercontent.com/78945582/127950129-089c7142-143a-41fc-8ecd-76c8a3711ba1.png)

![image](https://user-images.githubusercontent.com/78945582/127950078-c585ade6-c2ab-4645-9053-9af5903101d8.png)

**Comment by lixiangMindSpore** [comment]
![image](https://user-images.githubusercontent.com/78945582/127950183-5aeeb668-60e4-4a19-a50f-f5ace8c6b3a0.png)

**Comment by shiyu22** [comment]
Are you show tables in mysql database? That is, `use mysql` and then `show tables;`.

**Comment by lixiangMindSpore** [comment]
> Are you show tables in mysql database? That is, `use mysql` and then `show tables;`.

是的，最后一张图就是tables

**Comment by lixiangMindSpore** [comment]
我再发一遍
![image](https://user-images.githubusercontent.com/78945582/127950763-8fc39dbd-7cc6-45ca-b922-a1c81e4eb7f2.png)

**Comment by shiyu22** [comment]
It is possible that the table was not created successfully. Please check the log of the server and make sure MySQL has permission.

**Comment by lixiangMindSpore** [comment]
> It is possible that the table was not created successfully. Please check the log of the server and make sure MySQL has permission.

运行正常啊，应该是没问题的，milvus_img_search是在哪里查？麻烦您了

**Comment by lixiangMindSpore** [comment]
> It is possible that the table was not created successfully. Please check the log of the server and make sure MySQL has permission.

我用的都是源代码，没有改过

**Comment by shiyu22** [comment]
What's the logs in server? And docker logs?

**Comment by shiyu22** [comment]
not activate, closed.
