### ISSUE TITLE
 Modify the source code (start from 0 and add to the database, and the images with higher similarity to the existing pictures will not be stored), the code is shown in the text, but MILVUS_CLI is None

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#577]
```python
import os

from operations.load import do_load
from operations.search import do_search
from encode import Resnet50
from milvus_helpers import MilvusHelper
from mysql_helpers import MySQLHelper
from config import DEFAULT_TABLE

source_specific_one_img_path = "/data/SourceOneData/"
source_img_path = "/data/SourceData/"

def init_add_image(table_name, image_dir, model, milvus_client, mysql_cli):
    total_num = do_load(table_name, image_dir, model, milvus_client, mysql_cli)
    print('hahahahahahahahahahaha:  ' + str(milvus_client))


def write_log(img_path, paths):
    path = "./"
    import time
    localtime = time.localtime(time.time())
    time = time.strftime('%Y-%m-%d %H:%M:%S', localtime)
    with open(path + 'clean_record.txt', 'a', encoding='utf-8') as w:
        w.write(str(time) + ":   " + img_path + "  is similar with  " + paths)
        w.write('\r\n')
        w.close()


def write_delete_file(img_path):
    path = "./"
    with open(path + 'delete_file.txt', 'a', encoding='utf-8') as w:
        w.write(img_path)
        w.write('\r\n')
        w.close()


def main(table_name=DEFAULT_TABLE):
    MODEL = Resnet50()
    MILVUS_CLI = MilvusHelper()
    MYSQL_CLI = MySQLHelper()
    print("lalalalalalalalala:   " + str(MILVUS_CLI))

    init_add_image(table_name, source_specific_one_img_path, MODEL, MILVUS_CLI, MYSQL_CLI)
    listdir = os.listdir(source_img_path)
    for listdirname in listdir:
        path = os.path.join(source_img_path, listdirname)
        files = os.listdir(path)
        for filename in files:
            img_path = os.path.join(source_img_path, filename)
            paths, distances = do_search(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)
            if distances > 0.99:
                write_log(img_path, paths)
                write_delete_file(img_path)


if __name__ == '__main__':
    main()
```

![image](https://user-images.githubusercontent.com/78945582/127994916-a8f16899-f745-4ce5-8d81-135c149051a1.png)

**Comment by ss892714028** [comment]
Next time if you are posting code, please include syntax highlight.

**Comment by ss892714028** [comment]
Next time if you are posting code, please include syntax highlight.
You can refer to this guide: https://www.markdownguide.org/extended-syntax/

===================================================================
From what I can see, it's possible that there is something wrong connecting to the Milvus host.

Calling MilvusHelper() will initiate the class constructor. If you did not modify the MilvusHelper source code, the constructor tries to connect to the Milvus host. 

```python
def __init__(self):
    try:
        self.collection = None
        connections.connect(host=MILVUS_HOST, port=MILVUS_PORT)
        LOGGER.debug("Successfully connect to Milvus with IP:{} and PORT:{}".format(MILVUS_HOST, MILVUS_PORT))
    except Exception as e:
        LOGGER.error("Failed to connect Milvus: {}".format(e))
        sys.exit(1)
```

**Comment by lixiangMindSpore** [comment]
> Next time if you are posting code, please include syntax highlight.
> You can refer to this guide: https://www.markdownguide.org/extended-syntax/
> 
> ===================================================================
> From what I can see, it's possible that there is something wrong connecting to the Milvus host.
> 
> Calling MilvusHelper() will initiate the class constructor. If you did not modify the MilvusHelper source code, the constructor tries to connect to the Milvus host.
> 
> ```python
> def __init__(self):
>     try:
>         self.collection = None
>         connections.connect(host=MILVUS_HOST, port=MILVUS_PORT)
>         LOGGER.debug("Successfully connect to Milvus with IP:{} and PORT:{}".format(MILVUS_HOST, MILVUS_PORT))
>     except Exception as e:
>         LOGGER.error("Failed to connect Milvus: {}".format(e))
>         sys.exit(1)
> ```

谢谢您，通过代码调试，问题在于collection，我现在想通过table_name获取collection，有没有相关的获取函数？因为我上一次建立表的时候，该表下就对应了collection，每次创建新对象collection为空，但是表名对应的collection不为空，谢谢您，麻烦您了
![image](https://user-images.githubusercontent.com/78945582/128107730-84d715c5-2d97-486b-b445-f4a412526848.png)

**Comment by lixiangMindSpore** [comment]
我的诉求是，之前建立过mysql表名，导入新图片的时候，如果该图片与数据库已有的图片特征向量相似度较高，那就不加入数据库，否则加入，所以需要已有表名的collection，如果新创建对象，collection为空，就出现该issue的问题。

**Comment by shiyu22** [comment]
not activate, closed.
