### ISSUE TITLE
The milvus_img_search2 table has been deleted, but the table still exists in mysql, which is a bug

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#578]
**Describe the issue**
已经删除了milvus_img_search2表，但是运行代码仍然认为存在该表，是个bug

**To Reproduce**
Steps to reproduce the behavior(Docker or Source code):
1. 进入mysql的docker，use mysql;，删除milvus_img_search2表（如下图所示，注意，删除的是milvus_img_search2，不是milvus_img_search）；
![image](https://user-images.githubusercontent.com/78945582/128112615-095b5254-778b-4765-af72-7cd9d632669b.png)

2. 运行代码do_load(table_name, image_dir, model, milvus_client, mysql_cli)，表名为milvus_img_search2；
3. 在create_collection函数中却显示有该表，debug到if那一行，直接跳到return "OK"
![image](https://user-images.githubusercontent.com/78945582/128112387-04ef48b3-5cea-4493-a19e-5eb569a6165f.png)

**Expected behavior**
新的表名，应该成功创建对应的collection

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/128112435-0d70cd0c-066d-4447-95d7-810ebe05f54d.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
I think that you have deleted the table in MySQL, not Milvus. If you want to delete all the data, you are supposed to drop table in both MySQL and Milvus. And you can also call the API `/drop`.

**Comment by shiyu22** [comment]
not activate.
