### ISSUE TITLE
mishards: [docker run] start up failed...

### ISSUE THREAD

**Issue by LemonSqi** [milvus-io/bootcamp#582]
start up mishards through "docker run ... " failed

command details:
docker run -d --restart=always --name mishards -p 19531:19531 -p 19532:19532 -v /home/$USER/docker/mishards/db:/tmp/milvus/db -v /home/$USER/docker/mishards/conf/mishards_env:/source/mishards/.env mishards python3 mishards/main.py

terminal feedback:
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"python3\\\": executable file not found in $PATH\"\n".

now track -> echo $PATH  exists "/usr/local/python3/bin"
cd /usr/local/python3/bin

ll| grep python3

lrwxrwxrwx 1 root      root        9 Aug  3 17:04 python3 -> python3.7
-rwxrwxrwx 2 root      root 14000911 Aug  3 17:04 python3.7
lrwxrwxrwx 1 root      root       17 Aug  3 17:04 python3.7-config -> python3.7m-config
-rwxrwxrwx 2 root      root 14000911 Aug  3 17:04 python3.7m
-rwxrwxrwx 1 root      root     2910 Aug  3 17:04 python3.7m-config
lrwxrwxrwx 1 root      root       16 Aug  3 17:04 python3-config -> python3.7-config

Looking forward to reply!

**Comment by Bennu-Li** [comment]
Which document did you refer to when you ran this command?

**Comment by shiyu22** [comment]
not activate.
