### ISSUE TITLE
Milvus Server crashes when loading images in reversed image search demo

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#583]
**Describe the issue**
加载图片时，出现崩溃，[[A2021-08-05 11:37:36,029 ｜ ERROR ｜ grpc_handler.py ｜ ping ｜ 343 ｜ Retry to connect server 192.168.0.202:19530 failed.

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1 加载图片时，出现崩溃，[[A2021-08-05 11:37:36,029 ｜ ERROR ｜ grpc_handler.py ｜ ping ｜ 343 ｜ Retry to connect server 192.168.0.202:19530 failed.

**Expected behavior**
能够正常加载完图片

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/128287114-6bb70a74-1992-4ff0-b4d3-01b80ff60d9c.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
The error shows that the connection to the Milvus server has failed, so please check the Milvus server.

**Comment by shiyu22** [comment]
not activate.
