### ISSUE TITLE
After reinstalling Milvus, running reverse image search demo, cannot add image.

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#584]
**Describe the issue**
1.之前加载图片10几张后崩溃了
2. 重装milvus
3. 运行demo，点击+没反应

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1.之前加载图片10几张后崩溃了
2. 重装milvus
3. 运行demo，点击+没反应

**Expected behavior**
点击加号加载图片

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/128308709-db6b841e-2f6a-491a-b119-95e8be529bbf.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
Before running the server, please make sure all three Dockers are successfully started, including Milvus, server, and client. If the front-end's request does not respond, you can check the status of the request in your browser, or there may be a network problem.

**Comment by shiyu22** [comment]
not activate.
