### ISSUE TITLE
Reverse image search project, insert stuck at the last image.

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#585]
**Describe the issue**
点击demo的加号，加载图片到最后一张卡住不动

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. 点击demo的加号， 加载图片到最后一张卡住不动

**Expected behavior**
最后一张图片加载完成

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/128311981-805bb079-5e5c-4192-b5a2-0e7b9d2e6a8f.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
After extracting the feature vectors, it will insert the vectors into Milvus and insert ids to MySQL, which may be slow or hanged when inserting them. So in addition to these logs, you can wait and see if there are also error logs.

**Comment by shiyu22** [comment]
not activate.
