### ISSUE TITLE
Load 50,000 pictures, crashes when 2,000 images are loaded, my code is as shown in the text

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#586]
**Describe the issue**
要加载5万张图片，加载到2000张左右的时候崩溃了，我的代码如正文所示

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. 要加载5万张图片，加载到2000张左右的时候崩溃了，我的代码如正下文所示
`import os

from operations.load import do_load
from operations.search import do_search
from encode import Resnet50
from milvus_helpers import MilvusHelper
from mysql_helpers import MySQLHelper
from config import DEFAULT_TABLE
from logs import LOGGER
import sys

source_specific_one_img_path = "/data/SourceOneData/"
source_img_path = "/data/SourceData/"

# Combine the id of the vector and the name of the image into a list
def format_data(ids, names):
    data = []
    for i in range(len(ids)):
        value = (str(ids[i]), names[i])
        data.append(value)
    return data

def extract_img_features(img_path, model):
    try:
        feats = []
        names = []

        norm_feat = model.resnet50_extract_feat(img_path)
        feats.append(norm_feat)
        names.append(img_path.encode())
        return feats, names
    except Exception as e:
        LOGGER.error(" Error with extracting feature from image {}".format(e))
        sys.exit(1)

def add_one_image(table_name, image_dir, model, milvus_client, mysql_cli):
    total_num = do_load(table_name, image_dir, model, milvus_client, mysql_cli)

def write_log(img_path, paths):
    path = "./"
    import time
    localtime = time.localtime(time.time())
    time = time.strftime('%Y-%m-%d %H:%M:%S', localtime)
    with open(path + 'clean_record.txt', 'a', encoding='utf-8') as w:
        w.write(str(time) + ":   " + img_path + "  is similar with  " + paths[0])
        w.write('\r\n')
        w.close()

def write_delete_file(img_path):
    path = "./"
    with open(path + 'delete_file.txt', 'a', encoding='utf-8') as w:
        w.write(img_path)
        w.write('\r\n')
        w.close()

def main(table_name=DEFAULT_TABLE):
    MODEL = Resnet50()
    MILVUS_CLI = MilvusHelper()
    MYSQL_CLI = MySQLHelper()

    add_one_image(table_name, source_specific_one_img_path, MODEL, MILVUS_CLI, MYSQL_CLI)
    listdir = os.listdir(source_img_path)
    for listdirname in listdir:
        level_one_file = os.path.join(source_img_path, listdirname)
        files = os.listdir(level_one_file)
        for filename in files:
            img_path = os.path.join(level_one_file, filename)
            paths, distances = do_search(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)
            if distances[0] < 0.3:
                write_log(img_path, paths)
                write_delete_file(img_path)
            else:
                vectors, names = extract_img_features(img_path, MODEL)
                ids = MILVUS_CLI.insert(table_name, vectors)
                MILVUS_CLI.create_index(table_name)
                MYSQL_CLI.create_mysql_table(table_name)
                MYSQL_CLI.load_data_to_mysql(table_name, format_data(ids, names))

if __name__ == '__main__':
    main()
`

**Expected behavior**
能够正常加载完图片
**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/128331967-f0c42c67-564f-40b9-b5f4-c2cad6baf487.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
The screenshot shows that "Fail connecting to server", so please check if the Milvus server is running successfully.

**Comment by shiyu22** [comment]
not activate, closed.
