### ISSUE TITLE
When inserting the features of all pictures, the model should not be loaded every time

### ISSUE THREAD

**Issue by shantzhou** [milvus-io/bootcamp#590]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shiyu22** [comment]
Hi, thank you for the issue.

Actually, the model is only loaded once when starting the service, you can refer to [the code in main.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/main.py#L31). However, the [resnet50_extract_feat](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/encode.py#L18) function is called each time the image features are extracted, and then the vector is returned.

Best whishes.

**Comment by shiyu22** [comment]
not activate.
