### ISSUE TITLE
Error with extracting feature from image attempt to write a readonly database

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#591]
**Describe the issue**
基于milvus1.1.1版本，原先运行成功的脚本，隔几天后再运行时出现Error with extracting feature from image attempt to write a readonly database

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. 基于milvus1.1.1版本，原先运行成功的脚本，隔几天后再运行时出现Error with extracting feature from image attempt to write 

**Expected behavior**
基于milvus1.1.1版本，原先运行成功的脚本，再运行时不再出现错误

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/129152607-ae79ae4e-152f-4259-a73c-f7be139cd2f6.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 1.1.1]
 - Server: [e.g. 1.1.1]
 - Client: [e.g. 1.1.1]

**Additional context**

**Comment by shiyu22** [comment]
The error info shows the issue about the database, I think it's for Sqlite3. And you can follow [this answer](https://stackoverflow.com/questions/37897187/attempt-to-write-to-a-readonly-database-error) to solve it.

**Comment by shiyu22** [comment]
And please state your issue in English, and you can take a look at announcement #587.

**Comment by lixiangMindSpore** [comment]
> The error info shows the issue about the database, I think it's for Sqlite3. And you can follow [this answer](https://stackoverflow.com/questions/37897187/attempt-to-write-to-a-readonly-database-error) to solve it.

都是按照指导操作的，运行的也是main.py，网上的解决办法大部分不好使，麻烦提供一个指导，多谢
![image](https://user-images.githubusercontent.com/78945582/129155568-eb8c6531-13df-4e30-8a1a-d21d101c9665.png)

**Comment by shiyu22** [comment]
Please make sure that CacheDB has permissions. And you can close this issue if it has been resolved :)

**Comment by shiyu22** [comment]
not activate.
