### ISSUE TITLE
add object detection to video similarity search README

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/bootcamp#599]
**Is your feature request related to a problem? Please describe.**
Add object detection description to [video_similarity_search README](https://github.com/milvus-io/bootcamp/tree/master/solutions/video_similarity_search), just like [reverse_image_search README](https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search).

**Comment by jaelgu** [comment]
closed with https://github.com/milvus-io/bootcamp/commit/3dcfcf2c35557b389e2f2c7dec18c029d25aba57
