### ISSUE TITLE
text_search_engine example docker-compose up -d after docker logs show grpc link error 

### ISSUE THREAD

**Issue by ZGMF-mantou** [milvus-io/bootcamp#603]
按照quick_deploy/README.md执行到最后发现搜索不到结果，查看docker log发现在执行docker-compose up -d之后etdc与standalone的日志信息中都有error

etdc

> {"log":"{\"level\":\"warn\",\"ts\":1629684382.6415653,\"caller\":\"fileutil/fileutil.go:57\",\"msg\":\"check file permission\",\"error\":\"directory \\\"/etcd\\\" exist, but the permission is \\\"drwxr-xr-x\\\". The recommended permission is \\\"-rwx------\\\" to prevent possible unprivileged access to the data\"}\n","stream":"stderr","time":"2021-08-23T02:06:22.64210455Z"}
{"log":"{\"level\":\"info\",\"ts\":\"2021-08-23T02:06:23.345Z\",\"caller\":\"etcdserver/backend.go:81\",\"msg\":\"opened backend 

standalone

> {"log":"[2021/08/23 02:06:26.514 +00:00] [WARN] [logger.go:51] [\"grpc: addrConn.createTransport failed to connect to {localhost:53100  \u003cnil\u003e 0 \u003cnil\u003e}. Err :connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:53100: connect: connection refused\\\". Reconnecting...\"]\n","stream":"stdout","time":"2021-08-23T02:06:26.514591424Z"}
{"log":"[2021/08/23 02:06:26.514 +00:00] [WARN] [logger.go:51] [\"grpc: addrConn.createTransport failed to connect to {localhost:53100  \u003cnil\u003e 0 \u003cnil\u003e}. Err :connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:53100: connect: connection refused\\\". Reconnecting...\"]\n","stream":"stdout","time":"2021-08-23T02:06:26.514604624Z"}
{"log":"[2021/08/23 02:06:26.514 +00:00] [INFO] [logger.go:48] [\"pickfirstBalancer: HandleSubConnStateChange: 0xc0003046f0, {TRANSIENT_FAILURE connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:53100: connect: connection refused\\\"}\"]\n","stream":"stdout","time":"2021-08-23T02:06:26.514616824Z"}
{"log":"[2021/08/23 02:06:26.514 +00:00] [INFO] [logger.go:48] [\"pickfirstBalancer: HandleSubConnStateChange: 0xc000289bf0, {TRANSIENT_FAILURE connection error: desc = \\\"transport: Error while dialing dial tcp 127.0.0.1:53100: connect: connection refused\\\"}\"]\n","stream":"stdout","time":"2021-08-23T02:06:26.514628524Z"}
{"log":"[2021/08/23 02:06:26.515 +00:00] [DEBUG] [session_util.go:152] [\"Session get serverID success\"]\n","stream":"stdout","time":"2021-08-23T02:06:26.51599111Z"}

我分别在购买的香港服务器与公司的本地服务器（均为centos7）实验过都是相同的报错
请问有什么需要确认或者需要修改的地方嘛
[dockerlog.zip](https://github.com/milvus-io/bootcamp/files/7036167/dockerlog.zip)

**Comment by jingkl** [comment]
After looking at the logs, I see that your Milvus service did not start successfully, and that nodes like indexcoord, rootcoord, etc. were not linked successfully.
How does your installation look like？
You should be able to run the hello_milvus.py file if you start it successfully .
https://milvus.io/cn/docs/v2.0.0/example_code.md

**Comment by jingkl** [comment]
You can either uninstall the original installation and reinstall it later, or check that the ports on your machine are working

**Comment by ZGMF-mantou** [comment]
> After looking at the logs, I see that your Milvus service did not start successfully, and that nodes like indexcoord, rootcoord, etc. were not linked successfully.
> How does your installation look like？
> You should be able to run the hello_milvus.py file if you start it successfully .
> https://milvus.io/cn/docs/v2.0.0/example_code.md

我在本地目录下git clone了bootcamp项目，然后在/solutions/text_search_engine/quick_deploy目录下开始执行readme中的内容

> wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
sudo docker-compose up -d

这些然后到2.Start Server这步的时候似乎log里就开始报错了
![dir](https://user-images.githubusercontent.com/58501877/130585026-502e9ae4-f251-4ece-ad70-ade202d46409.png)
您说的使用hello_milvus.py来测试的意思是说单纯运行text_search_engine/quick_deploy/README.md下的步骤前还需要先安装好milvus2.0嘛，我以为docker-compose up -d那步就是安装docker版并运行了0.0

**Comment by ZGMF-mantou** [comment]
端口状态如下
![port](https://user-images.githubusercontent.com/58501877/130585939-4073a785-48bd-44ed-8a24-da6c38cdf54d.png)

**Comment by ZGMF-mantou** [comment]
我按照流程用1.1版本倒是可以正常访问5000/doc
但是上传文件的时候还是出了问题
![083000](https://user-images.githubusercontent.com/58501877/131321909-2f4bdf2d-257d-47d9-8912-fef5c1e32dae.png)
![083001](https://user-images.githubusercontent.com/58501877/131321920-54f04cf8-6733-463e-b968-d156ad94d858.png)

quick_deploy/Milvus-bert-server/src/logs下的log文件如下
[milvus-2021-08-30.log](https://github.com/milvus-io/bootcamp/files/7075855/milvus-2021-08-30.log)

请问有哪里需要更改嘛0.0

**Comment by ZGMF-mantou** [comment]
Exception: The vector dimension must be equal to the collection dimension
看到个这句，我只按照教程设置了Milvus-bert-server/src/config.py里VECTOR_DIMENSION为2048，那个collection dimension是哪里设置的0.0

**Comment by jingkl** [comment]
Why 2048 dimensions, VECTOR_DIMENSION defaults to 768 in config.py, and this is not a parameter that can be made, because the vector generated by the bert model is also 768.

**Comment by jingkl** [comment]
Long time no reply，closed it
