### ISSUE TITLE
I intend to search multitudes of images one time, how to modify the interface "do_search(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)"

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#606]
**Is your feature request related to a problem? Please describe.**
I intend to search multitudes of images one time, how to modify the interface "do_search(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)"

**Describe the solution you'd like**
give me an example code about searching many images one time

**Describe alternatives you've considered**

**Additional context**

**Comment by lixiangMindSpore** [comment]
not just

> Got it, it's a good idea for retrieving multiple images.
> 
> And I think it is necessary to add a `/folder/search` interface to [main.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/main.py), where can search by the path of images or zip of multiple images.
> 
> For example, you can modify the `img_path` in the `do_search(table_name, img_path, MODEL, MILVUS_CLI, MYSQL_CLI)` function to `img_folder`, and then call `model.resnet50_extract_feat(img_path)` in turn when extracting the feature vector, will return a list of vectors, that can search directly in Milvus.
> 
> If you have finished the interface, you can submit a [Pull Request](https://github.com/milvus-io/bootcamp/pulls) for the Bootcamp, and feel free to contact me if you have any questions, and looking forward to your contribution.

Not only search multitudes of images, but also spend less time than before.

**Comment by shiyu22** [comment]
> Not only search multitudes of images but also spend less time than before.

If you want to increase Milvus' performance, that would be a whole other topic. This issue is about adding the feature "search with nq>1" to the reversed image search solution's backend. You can start a discussion here (https://github.com/milvus-io/milvus/discussions) or open another issue on Milvus' repository (https://github.com/milvus-io/milvus/issues).

**Comment by avats-dev** [comment]
@shiyu22 I want to tackle this one. From what I have read in the code, I inferred following things:

- In current [`/img/search`](https://github.com/milvus-io/bootcamp/blob/c5150d974a9e4c0594e91176710cc47ebe80134c/solutions/reverse_image_search/quick_deploy/server/src/main.py#L102) , we are getting lists of **paths and distances** from [`do_search`](https://github.com/milvus-io/bootcamp/blob/c5150d974a9e4c0594e91176710cc47ebe80134c/solutions/reverse_image_search/object_detection/server/src/operations/search.py#L21) function and we are storing them in a dictionary and sorting it by the distances. 
- Now, in `do_search` function, I am not able to understand how [`run`](https://github.com/milvus-io/bootcamp/blob/c5150d974a9e4c0594e91176710cc47ebe80134c/solutions/reverse_image_search/object_detection/server/src/operations/search.py#L26) function have been used. 
- Also, I don't know how to use `async` and `await` keywords.

I think in multiple image search, we can generate search for images one by one (through existing methods) and store it as a dict of dict and return it. 

> However, if the question here is to get all possible similar images as a whole to a bunch of given query images, we can store ids in a `set` to avoid duplicate elements and similarly for distances and return it.

Please assist me how should I approach this. I am looking forward to resolve this one. Thanks 🎉

**Comment by shiyu22** [comment]
Hi @avats-dev, sorry to reply to your message now, but very glad you want to contribute :)

I think that you are right, you can call the `do_search` interface multiple times, then save it as a dict and return it.
>  - In current /img/search , we are getting lists of paths and distances from do_search function and we are storing them in a dictionary and sorting it by the distances. (As you said, it will return a list containing TOP_K results)
> - Now, in do_search function, I am not able to understand how run function have been used. (I think `do_search` has not `ru`n function in the latest code, if you mean `run` in main.py, it was the function for FastAPI to run the app code)
> - Also, I don't know how to use async and await keywords. (The `async` is used for asynchronous functions, we use it by default, and `await` is for uploading image data, you don’t need it)

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
