### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by miladfa7** [milvus-io/bootcamp#612]
i try run reverse_image_search.ipynb but but I make a error in executing the last cell

**Run Last Cell** 
```
for x in range(len(results)):
    query_file = search_images[x]
    result_files = [red.get(y.id).decode('utf-8') for y in results[x]]
    distances = [y.distance for y in results[x]]
    show_results(query_file, result_files, distances)
```
**Error:** 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-24-84281ccaffc2> in <module>
      5         print(red.get(y.id))
      6     print(len(results))
----> 7     result_files = [red.get(y.id).decode('utf-8') for y in results[x]]
      8     distances = [y.distance for y in results[x]]
      9     show_results(query_file, result_files, distances)

<ipython-input-24-84281ccaffc2> in <listcomp>(.0)
      5         print(red.get(y.id))
      6     print(len(results))
----> 7     result_files = [red.get(y.id).decode('utf-8') for y in results[x]]
      8     distances = [y.distance for y in results[x]]
      9     show_results(query_file, result_files, distances)

AttributeError: 'NoneType' object has no attribute 'decode'
```
---------------------------------------------------------------------------------------------
**Trace**: 
(distance: 0.0, score: 0.0, id: 427408011447240044)
None
(distance: 0.0, score: 0.0, id: 427408011447239514)
None
(distance: 0.0, score: 0.0, id: 427408011447240477)
None
(distance: 0.0, score: 0.0, id: 427408011447239003)
None
(distance: 0.0, score: 0.0, id: 427408011447240328)
None
3

**Comment by shiyu22** [comment]
Can you check the value of the `results` and see if it is `None`?

**Comment by miladfa7** [comment]
> Can you check the value of the `results` and see if it is `None`?

yes, value of the results is None

**Comment by jaelgu** [comment]
Can't reproduce with rc5 using pymilvus. Can you specify your pymilvus (or pymilvus-orm) and milvus versions? @miladfa7

**Comment by miladfa7** [comment]
> Can't reproduce with rc5 using pymilvus. Can you specify your pymilvus (or pymilvus-orm) and milvus versions? Also did you modify any lines in reverse_image_search.ipynb? @miladfa7

**I installed it**

```
pymilvus_orm =='2.0.0rc1'
milvus == '0.0.63'
```

In this file ([requirements.txt)](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/requirements.txt) it is said to install this version of  pymilvus-orm==2.0.0rc1

**Comment by jaelgu** [comment]
@miladfa7 Please always make sure CONSISTENT milvus version & pymilvus_orm are installed. Currently reverse_image_search.ipynb in main branch uses v2.0.0rc2 for both milvus & pymilvus_orm.

**Comment by miladfa7** [comment]
@jaelgu  Yes that's right, thank you very much for your help. 

I want to install **milvus**, I get this error
Clone github repository.
```
$ git clone https://github.com/milvus-io/milvus.git
$ cd milvus/
$ ./scripts/install_deps.sh
=> $ make
```
Error:
```
make: go: Command not found
Building Milvus cpp library ...
bash: /home/milad/Desktop/Image: No such file or directory
make: *** [Makefile:101: build-cpp] Error 127
```

Do you have a solution?

**Comment by miladfa7** [comment]
> @miladfa7 Please always make sure CONSISTENT milvus version & pymilvus_orm are installed. Currently reverse_image_search.ipynb in main branch uses v2.0.0rc2 for both milvus & pymilvus_orm.

Please Help me

**Comment by jaelgu** [comment]
@miladfa7 How did you install milvus and what's your environment? Also you can take a look at https://milvus.io/docs/overview.md for installation guide (menu > Get Started > Install Milvus)
