### ISSUE TITLE
vgg+milvus的demo搜索不出结果列表

### ISSUE THREAD

**Issue by javahook** [milvus-io/bootcamp#62]
1，web界面
![image](https://user-images.githubusercontent.com/12382879/70122755-276f1a00-16ac-11ea-80d4-4cbb815e79b2.png)

2，docker容器
![image](https://user-images.githubusercontent.com/12382879/70122638-fee72000-16ab-11ea-87a0-e0c6b4ca9311.png)

**Comment by javahook** [comment]
GPU Name: GeForce GT 720
server_config.yaml
    cpu_cache_capacity: 8
   gpu_cache_capacity: 1

**Comment by JackLCL** [comment]
Can you run milvus example successfully?
https://milvus.io/docs/zh-CN/userguide/example_code/

**Comment by javahook** [comment]
> Can you run milvus example successfully?
> https://milvus.io/docs/zh-CN/userguide/example_code/
I did not run the python example .
But I can demploy and run milvusdb/milvus docker image (milvus 0.5.3)  on docker hub successfully.

**Comment by JackLCL** [comment]
You'd better to run example to check the status of milvus.

**Comment by javahook** [comment]
@JackLCL I run Milvus example[python3 example] on the milvusdb/milvus:cpu-latest successfully.
But can not list the search result yet.

**Comment by javahook** [comment]
建立容器(zilliz_search_images_demo, pic_search_demo_web)的时候，ip指定的是127.0.0.1
