### ISSUE TITLE
milvus2.0.0rc5 requirement.txt problem

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#635]
**Describe the issue**
The conflict is caused by:
    pymilvus 2.0.0rc5 depends on grpcio==1.37.1
    tensorflow 2.5.1 depends on grpcio~=1.34.0

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. pip install -r requirement.txt

**Expected behavior**
pip install -r requirement.txt success

**Screenshots**
![image](https://user-images.githubusercontent.com/78945582/131969223-610067fb-638e-47f3-b8ae-c3958418e55a.png)

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc5]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
Hi, thanks for your issue.

This is indeed a version conflict, it can solve by specifying the tensorflow version as 2.6.0, so needs changed **requirements.txt**, can you update it and submit us a PR?

Looking forward to having you as a contributor to Bootcamp.

**Comment by lixiangMindSpore** [comment]
> Hi, thanks for your issue.
> 
> This is indeed a version conflict, it can solve by specifying the tensorflow version as 2.6.0, so needs changed **requirements.txt**, can you update it and submit us a PR?
> 
> Looking forward to having you as a contributor to Bootcamp.

No problem!

**Comment by shiyu22** [comment]
Looking forward to your pull request :)
