### ISSUE TITLE
 fails to get the MilvusHelper object

### ISSUE THREAD

**Issue by akimisr** [milvus-io/bootcamp#636]
**Describe the issue**
My Milvus often fails to get the MilvusHelper object.At that time,I had to reinstall Milvus.This problem happens frequently.

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. Start standalone milvus2.0
2. Start reverse_image_search
3. Vist 127.0.0.1:5010/docs
4. Try to load or search some images
5. See an error

**Expected behavior**
Can always get milvushelper object.

**Screenshots**
Traceback (most recent call last):
  File "/home/vector/milvus2.0/quick_deploy/server/src/milvus_helpers.py", line 59, in insert
    mr = self.collection.insert(data)
AttributeError: 'NoneType' object has no attribute 'insert'

**Additional context**
Sometimes I use load.py from outside, which may be related to the problem.

**Comment by shiyu22** [comment]
Are there any logs in the server? Before calling the `collection.insert` function, we will first create a collection, you can view [the code](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py#L51), so it may fail when creating the collection.

This error means that the collection object is None, please double check whether your Milvus server is running successfully :)

**Comment by akimisr** [comment]
Only the log showing the normal operation of sever.I just use the code of MilvusHelper in object-search to create a collection.I think the error means Milvus server is not running.

**Comment by akimisr** [comment]
> Are there any logs in the server? Before calling the `collection.insert` function, we will first create a collection, you can view [the code](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py#L51), so it may fail when creating the collection.
> 
> This error means that the collection object is None, please double check whether your Milvus server is running successfully :)

Only the log showing the normal operation of sever.I just use the code of MilvusHelper in object-search to create a collection.I think the error means Milvus server is not running.

**Comment by akimisr** [comment]
> Are there any logs in the server? Before calling the `collection.insert` function, we will first create a collection, you can view [the code](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py#L51), so it may fail when creating the collection.
> 
> This error means that the collection object is None, please double check whether your Milvus server is running successfully :)

Only the log showing the normal operation of server.I just use the code of MilvusHelper in object-search to create a collection.I think the error means Milvus server is not running.

**Comment by shiyu22** [comment]
I think you are right, so how is your Milvus server?

**Comment by shiyu22** [comment]
same to #643
