### ISSUE TITLE
Error : `search_data` value is illegal  

### ISSUE THREAD

**Issue by miladfa7** [milvus-io/bootcamp#644]
i run this code 

```
import time
search_params = {"metric_type": "L2", "params": {"nprobe": 32}}
start = time.time()
results = collection.search(embeddings, "vector", param=search_params, limit=5, expr=None)
end = time.time() - start

print("Search took a total of: ", end)
results
```

but after executing this code this error:

```
<ipython-input-21-83993d13e2b0> in <module>
      4 search_params = {"metric_type": "L2", "params": {"nprobe": 32}}
      5 start = time.time()
----> 6 results = collection.search(embeddings, "vector", param=search_params, limit=5, expr=None)
      7 end = time.time() - start
      8 
```
```
ParamError: `search_data` value [[1.1281071  2.4604707  0.03646877 ... 0.09850642 0.4084255  3.1444438 ]
 [0.09859965 0.16395378 1.3809936  ... 1.3002781  0.06952193 0.63280797]
 [0.6615478  0.41407162 1.9169595  ... 0.41716254 1.0959387  1.3469244 ]] is illegal
```

**Comment by shiyu22** [comment]
Which version of Milvus are you using? Which branch are you running the script on?

**Comment by miladfa7** [comment]
> Which version of Milvus are you using? Which branch are you running the script on?

Milvus version = '0.0.63'
pymilvus version = 2.0.0rc5
branch = v2.0.0rc5

for Install Milvus Standalone i use  this link 
https://milvus.io/docs/v2.0.0/install_standalone-docker.md

**Comment by Bennu-Li** [comment]
Is your embeddings in numpy format? Try to convert embedding to list format before searching:
embeddings = embeddings.tolist()

**Comment by miladfa7** [comment]
> Is your embeddings in numpy format? Try to convert embedding to list format before searching:
> embeddings = embeddings.tolist()

thank you, solved.
