### ISSUE TITLE
Please change all "Recommendation system" to "recommender system".

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/bootcamp#649]
**Describe the issue**
As suggested by Jun Gu, from now on we should only say "recommender system".

**To Reproduce**

**Expected behavior**
Replace all "recommendation system" with "recommender system". 

**Screenshots**

**Software version (please complete the following information):**

**Additional context**

**Comment by Giriraj-Roy** [comment]
I would like to work on this. Can you guide me if I have to update only the readme file or some other file also ?

**Comment by shiyu22** [comment]
Of course, welcome to be a contributor of the community.

You are supposed to modify all the files in master, such as the README and folder name.

**Comment by shiyu22** [comment]
Closed by #654
