### ISSUE TITLE
Pick an issue and become a Bootcamp contributor!

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/bootcamp#650]
## Good First Issue
These issues are relatively simple tasks that are supposed to take less than 30 minutes to fix, best suited for people who have limited experience in Milvus and its surrounding tools. 

## How to pick one?
If you see an issue that you want to work on, simply follow the link and go to the issue page; if there is no assignee for that issue, type **/assign @your_github_name** in the comment section to assign this issue to yourself.

| ID | Issue                                                  | Description                                                                                                                          | Assignee | Status |
|----|---------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|----------|--------|
| 0  | #649 | Please change all "Recommendation system" to "recommender system"                                                                    |    @Giriraj-Roy      |   Complete #655     |
| 1  | #643 | Failed to search vectors in Milvus:Index out of range And Failed to load data to Milvus: 'NoneType' object has no attribute 'insert' |   @avats-dev       |   Complete #808      |
| 2  | #606 | I intend to search multitudes of images one time                                                                                     |         |         |
| 3  | #658 | The number of images returned is different from TopK         |   @RafaelDSS      |Complete #792|
| 4  | #720 | Upgrade our issue templates to use GitHub issue forms |  @Hard-Coder05 | Complete #722 |
| 5  | #790  | [BUG]: reverse_image_search failed while run with custom MYSQL_PORT         |   @matrixji       |Complete #791 |
| 6  | #800 | [BUG]: BaseException: (code=1, message=round_decimalnot found in search_params) | @DerekChia | Complete #801 |
| 7  | #807  | [Feature Request]: The question_answer_system cannot improt Chinese        |         |    |
| 8 | #821 | [FEATURE]: Reverse image search based on image hashes | @generalZman | Done #858 |

**Comment by chukkyiii** [comment]
Hey I was wondering  there any new 'simple' tasks?

**Comment by mertbozkir** [comment]
Are there any new issue for hacktoberfest-2022?

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here.
