### ISSUE TITLE
Broken link in bootcamp/solutions/text search engine

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/bootcamp#651]
**Describe the issue**
The link to notebook in bootcamp/solutions/text search engine is broken

**To Reproduce**
- Which solution are you running? Please post the link.
- Steps to reproduce the behavior(Docker or Source code):
1. Go to 'https://github.com/milvus-io/bootcamp/tree/master/solutions/text_search_engine'
2. Click on 'notebook'
3. See an error: 404 error

**Expected behavior**
Fix the broken link

**Screenshots**

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]

**Additional context**

**Comment by shiyu22** [comment]
Thanks, and I think there is a space in the file name, will update it.

**Comment by shiyu22** [comment]
closed by #652
