### ISSUE TITLE
milvus 2.0.0-benchmark test result !

### ISSUE THREAD

**Issue by wolfju** [milvus-io/bootcamp#680]
I was researching milvus2.0.0 performance ,but i couldn't find the latest performance test result, and  i noticed the pictures under the pic folder ,but they were updated two years ago and not detailed , could you provide this  test result . Thank you 🙏 !

**Comment by Bennu-Li** [comment]
Currently Milvus2.0 is the release candidate, we will provide test results after the General Availability is released. Reference for release time: https://milvus.io/docs/v2.0.0/roadmap.md

If necessary, you can see the test results of Milvus1.0 as a reference: https://github.com/milvus-io/bootcamp/blob/1.1/benchmark_test/performance_benchmark.md

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
