### ISSUE TITLE
A broken link

### ISSUE THREAD

**Issue by yhmo** [milvus-io/bootcamp#702]
**Describe the issue**
In this page: https://github.com/milvus-io/bootcamp/blob/1.1/benchmark_test/lab1_sift1b_1m.md

This sentence: 
Before testing, please modify the corresponding parameters according to the script instructions

The "script instructions" point to https://github.com/milvus-io/bootcamp/blob/1.1/benchmark_test/scripts/EN_README.md
This link is not available.
The correct link address should be:
https://github.com/milvus-io/bootcamp/blob/1.1/benchmark_test/scripts/README.md

**Comment by JackLCL** [comment]
fixed.
