### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms

### ISSUE THREAD

**Issue by Hard-Coder05** [milvus-io/bootcamp#720]
## Title
GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

## Description
This repository currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use this repo's issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
I would like to work on this!

**Comment by Hard-Coder05** [comment]
@shiyu22 Please assign me this issue! I will be more than happy to workon this!

**Comment by shiyu22** [comment]
That's a good idea, thanks very much. :)
