### ISSUE TITLE
[BUG]: [benchmark][Recall test] recall value is diff when search the same data

### ISSUE THREAD

**Issue by wulc2021** [milvus-io/bootcamp#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi ,i  run the https://github.com/milvus-io/bootcamp/blob/master/benchmark_test/lab1_sift1b_1m.md test.  
## Expand data
In order to run the Dim = 512, i expand the 1 million test data which Dim = 128, here the script expand data:
Expand the "milvus_sift1m" and "query_data" from Dim = 128 -> Dim = 256/512/1024
~~~
for j in [2, 4, 8]:
  # insert data
  for i in range(10):
    filename =  '/milvus_sift1m_128/binary_128d_00' + str(i).zfill(3) + '.npy'
    outfilename = '/milvus_sift1m_' + str(j*128) +'/binary_128d_00' + str(i).zfill(3) + '.npy'
    data = np.load(filename)
    data = np.tile(data, j)
    # data = data.tolist()
    np.save(outfilename, data)

    print("output dim = " + str(j*128) + "; file = " + str(i))
  # query data
  query_filename =  '/query_data_128/query.npy'
  query_outfilename = '/query_data_' + str(j*128) + '/query.npy'
  data = np.load(query_filename)
  data = np.tile(data, j)
  # data = data.tolist()
  np.save(query_outfilename, data)

~~~
## Script run the recall test
~~~
path=$(pwd)
indextype='cpu'
dataset=1m
file_size=2048

# python3 main.py --show
for M in 32
  do
    PQ_M="PQ_M = ${M}"
    line=`sed -n '/PQ_M/=' ${path}/config.py`
    sed -i "$line d" ${path}/config.py
    sed -i "$line i$PQ_M" ${path}/config.py

    for dim in 512
      do
        data="data$dim"
        BASE_FILE_PATH="BASE_FILE_PATH = '${path}/${data}/milvus_sift${dataset}'"
        line=`sed -n '/BASE_FILE_PATH/=' ${path}/config.py`
        sed -i "$line d" ${path}/config.py
        sed -i "$line i$BASE_FILE_PATH" ${path}/config.py

        QUERY_FILE_PATH="QUERY_FILE_PATH = '${path}/${data}/query_data'"
        line=`sed -n '/QUERY_FILE_PATH/=' ${path}/config.py`
        sed -i "$line d" ${path}/config.py
        sed -i "$line i$QUERY_FILE_PATH" ${path}/config.py

        RECALL_QUERY_FILE="RECALL_QUERY_FILE = '${path}/${data}/query_data/query.npy'"
        line=`sed -n '/RECALL_QUERY_FILE/=' ${path}/config.py`
        sed -i "$line d" ${path}/config.py
        sed -i "$line i$RECALL_QUERY_FILE" ${path}/config.py

        GROUNDTRUTH_FILE="GROUNDTRUTH_FILE = '${path}/${data}/gnd/ground_truth_1m.txt'"
        line=`sed -n '/GROUNDTRUTH_FILE/=' ${path}/config.py`
        sed -i "$line d" ${path}/config.py
        sed -i "$line i$GROUNDTRUTH_FILE" ${path}/config.py

        # special case for file size
        # if [ $dim == 256 ];then
        #   file_size=1216
        # elif [ $dim == 512 ];then
        #   file_size=2432
        # else
        #   file_size=4864
        # fi

        INDEX_FILE_SIZE="INDEX_FILE_SIZE = ${file_size}"
        line=`sed -n '/INDEX_FILE_SIZE/=' ${path}/config.py`
        sed -i "$line d" ${path}/config.py
        sed -i "$line i$INDEX_FILE_SIZE" ${path}/config.py
        
        python3 main.py --collection "ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --dim $dim -c
        python3 main.py --collection "ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --index pq --build 
        python3 main.py --show
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --load
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --index=pq --build 

        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --rows
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --flush
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --rows
        sleep 200s

        python3 main.py --collection "ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --describe_index
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --search_param 128 --recall
        rm ./recall_result -rf

        # python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --search_param 1 --performance
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --drop_index
        python3 main.py --collection="ann_${dataset}_pq_${dim}_M_${M}_${indextype}" --drop

      done

  done
~~~

## Recall test with same data
And chage in bootcamp/benchmark_test/scripts/milvus_toolkit.py:128, in order to user the first nq vector, so every recall test  use the same search vector:
~~~
rand = [i for i in range(0, nq)] 
~~~
I found diff recall with same data, i think it will be the data load unsucessful. But when i load data and then wait a long time, it will get the same recall.

## Here the result get:
1、
![image](https://user-images.githubusercontent.com/28723868/137055878-a097fc94-c904-4b4a-830a-ac4eacc962d4.png)
2、
![image](https://user-images.githubusercontent.com/28723868/137055907-e41b62f9-e7f3-44e0-98fc-52b05aadfd68.png)

### Expected Behavior

The recall test the same with the same data.

### Software version

```markdown
- Milvus version:  1.0.0
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v1.0.0):
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 
- GPU: no
- Others:
```

**Comment by Bennu-Li** [comment]
The test result is no problem.
You recreated a new collection and index before both recall tests. For the same data and parameters, the index created each time will have some subtle differences, because the initialization will randomly select a seed when creating the index. But this will not have a great impact on the search results, and you can also see from your test results that the difference in the recall rate between the two is small. If you want to know more details, you can read IVF_PQ related articles and source code.

**Comment by wulc2021** [comment]
> Can you take a few more tests and let me know the results of your recall test?

sure, here the results of recall test. test the Dim = 128/256/512

### Dim = 128
①first
![图片](https://user-images.githubusercontent.com/28723868/137662863-dfb7c62c-a83d-4c2f-bc90-ae7783ede485.png)

②second
![图片](https://user-images.githubusercontent.com/28723868/137662884-c24adf06-192b-48b9-a10b-a2f825ded439.png)

### Dim = 256
①first
![图片](https://user-images.githubusercontent.com/28723868/137663249-44dd362c-7d05-4c2f-bda9-d888eb96d511.png)

②second
![图片](https://user-images.githubusercontent.com/28723868/137663266-a2c29470-f3a7-4c4f-b380-81c6045ae8a6.png)

### Dim = 512
①first
![图片](https://user-images.githubusercontent.com/28723868/137663616-bab7a552-0214-42ec-bb95-869583a1a2b7.png)

②second
![图片](https://user-images.githubusercontent.com/28723868/137663734-1c29b06c-abbe-4b79-8171-d278f2b80a86.png)

## Here the new found
I down load the level2 centroids,  in milvus/core/src/index/thirdparty/faiss/IndexIVFPQ.cpp:65
the function
```
void IndexIVFPQ::train_residual (idx_t n, const float *x)
{
    printf("=========faiss ivfpq begin to train!=========\n");
    train_residual_o (n, x, nullptr);
    printf("=========faiss ivfpq train ok!=========\n");
    std::string path = "./level2.txt";
    std::ofstream outfile;
    outfile.open(path);
    for (int i = 0; i < 256; i++) {
        std::string temp;
        for (int j = 0; j < d; j++) {
            temp += std::to_string(pq.centroids[i * d + j]) + " ";
        }
        outfile << temp << "\n" ;
    }
    std::cout << "save pq levele centroids!" << std::endl;
}
```
I found dim = 128, the recall test have the same result and the same centroids. dim = 256/512 have the diff recall test and diff centroids.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
