### ISSUE TITLE
你好，我在docker启动后，load_images没有反应 是怎么回事呢？

### ISSUE THREAD

**Issue by zlszhonglongshen** [milvus-io/bootcamp#77]
![image](https://user-images.githubusercontent.com/9023908/70488031-4e0cd500-1b32-11ea-85c9-3555c28067b0.png)

**Comment by JackLCL** [comment]
Can you run Milvus example?

**Comment by zlszhonglongshen** [comment]
> Can you run Milvus example?

已经解决 谢谢大佬
