### ISSUE TITLE
VGG+Milvus demo can't list result.

### ISSUE THREAD

**Issue by javahook** [milvus-io/bootcamp#80]
@JackLCL I run Milvus example[python3 example] on the milvusdb/milvus:cpu-latest successfully.
But can not list the search result yet.

_Originally posted by @javahook in https://github.com/milvus-io/bootcamp/issues/62#issuecomment-563819701_

**Comment by JackLCL** [comment]
The  VGG+Milvus demo is based on Milvus0.5.3 now. We don't  test it on Milvus0.6.0 cpu version. We will support it  soon.
