### ISSUE TITLE
[Feature Request]:  The question_answer_system cannot improt Chinese

### ISSUE THREAD

**Issue by mysunnyshine** [milvus-io/bootcamp#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

导入英文没问题，但是导入中文会出错
![Uploading image.png…]()

### Expected Behavior

期望导入中文也正常

### Steps To Reproduce

```markdown
按照 2.0 教程必现
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc7]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
not activate.
