### ISSUE TITLE
建立容器(zilliz_search_images_demo, pic_search_demo_web)时，ip指定的是127.0.0.1

### ISSUE THREAD

**Issue by javahook** [milvus-io/bootcamp#81]
建立容器(zilliz_search_images_demo, pic_search_demo_web)的时候，ip指定的是127.0.0.1

_Originally posted by @javahook in https://github.com/milvus-io/bootcamp/issues/62#issuecomment-564440080_

**Comment by JackLCL** [comment]
由于docker容器之间相互隔离的机制，当你在启动 pic_search_demo docker，将MILVUS_HOST指定为127.0.0.1，那么在 pic_search_demo docker内部访问127.0.0.1:19530时，是不能访问到milvus docker里面milvus服务的。
   所以，在启动 pic_search_demo docker时，需要将MILVUS_HOST指定为一个ipv4地址。

**Comment by javahook** [comment]
改成指定ipv4后结果出来了。
![image](https://user-images.githubusercontent.com/12382879/70607077-c493fa80-1c38-11ea-9248-e80b97cd999c.png)
