### ISSUE TITLE
[FEATURE]: Reverse image search based on image hashes

### ISSUE THREAD

**Issue by generalZman** [milvus-io/bootcamp#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

My team wanted to search image similarity based on hashes. I couldn't find any tutorial or documenation for it

### Describe the solution you'd like

A Jypyter Notebook based tutorial to get started. Since Milvus doesn't support string types, converting hashes to binary vector is the way to go

### Describe alternatives you've considered

A Docker deployable solution

### Anything else?

N/A

**Comment by shiyu22** [comment]
closed by #858
