### ISSUE TITLE
cannot find milvus_bootcamp.py and get_id.sh

### ISSUE THREAD

**Issue by wjtan99** [milvus-io/bootcamp#90]
Can you help?

**Comment by JackLCL** [comment]
Which milvus version do you use?

**Comment by wjtan99** [comment]
v0.6. Should I use this repo for bootcamp?

**Comment by JackLCL** [comment]
Yes, you can only find milvus_bootcamp.py and get_id.sh in milvus0.3.1.

**Comment by wjtan99** [comment]
is there a bootcamp for v0.6 then?  
Thanks.

**Comment by JackLCL** [comment]
Yes, bootcamp for 0.6.0 has published.
