### ISSUE TITLE
[BUG]:  can not creat a IVF_SQ8 for a BINARY_VECTOR based JACCARD

### ISSUE THREAD

**Issue by holyzing** [milvus-io/bootcamp#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

METRIC_TYPE = os.getenv("METRIC_TYPE", "JACCARD") 

field2 = FieldSchema(name="embedding", dtype=DataType.BINARY_VECTOR, descrition="binary vector", dim=VECTOR_DIMENSION, is_primary=False) 

default_index= {"index_type": "IVF_SQ8", "metric_type": METRIC_TYPE, "params": {"nlist": 16384}} 
 

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
Actually, BINARY_VECTORS can only create `BIN_IVF_FLAT` index, you can refer to [this page](https://milvus.io/docs/v2.0.0/metric.md#binary).

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
