### ISSUE TITLE
[BUG]: Error with 'NoneType' object has no attribute 'count_entities' images in this set

### ISSUE THREAD

**Issue by Yezi-cmd** [milvus-io/bootcamp#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempt to open 192.168.1.122:8001,but Page error:Error with 'NoneType' object has no attribute 'count_entities' images in this set.
And app.log show  : 
        milvus.client.grpc_handler - ERROR - Retry to connect server 192.168.1.122:19530 failed.
        root - ERROR - Fail connecting to server on 192.168.1.122:19530. Timeout
        root - ERROR - 'NoneType' object has no attribute 'count_entities'
But 192.168.1.122:19530 is working.  localhost telnet  192.168.1.122:19530  also pass.

### Software version

```markdown
Milvus: milvus:1.0.0-cpu-d030521-1ea92e
Server: 1.0
Client: 1.0
pymilvus:1.0.1
```

**Comment by ss892714028** [comment]
From "Fail connecting to server on 192.168.1.122:19530. Timeout", it shows that Pymilvus failed to connect to the Milvus server. First, check if the Milvus server is running properly and then I would suggest manually connecting to Milvus using Pymilvus.

**Comment by Yezi-cmd** [comment]
“I would suggest manually connecting to Milvus using Pymilvus”？？  How to  manually  connecting to Milvus using Pymilvus？？

**Comment by ss892714028** [comment]
https://milvus.io/api-reference/pymilvus/v2.0.0rc8/tutorial.html

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
