### ISSUE TITLE
[BUG]: ERROR: No matching distribution found for pandas==1.2.4; python_version > "3.6"

### ISSUE THREAD

**Issue by Yezi-cmd** [milvus-io/bootcamp#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to pip install pymilvus==2.0.0rc6, 
        ERROR: Could not find a version that satisfies the requirement pandas==1.2.4; python_version > "3.6" (from pymilvus) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
      ERROR: No matching distribution found for pandas==1.2.4; python_version > "3.6"
python is 3.7
numpy：1.21.3
I can not install pandas==1.2.4，should I can do？？

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by jaelgu** [comment]
@Yezi-cmd What is your python & pip version? Check it with `python --version` and `pip --version`. Make sure it's >python3.6

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd What is your python & pip version? Check it with `python --version` and `pip --version`. Make sure it's >python3.6

python 3.7  and pip 21.3.1

**Comment by jaelgu** [comment]
@Yezi-cmd I've tried in virtual env with python3.7 and & pip 21.3.1. But I can't reproduce your issue with `pip install pymilvus==2.0.0rc6`. It looks like problem with your environment.

![image](https://user-images.githubusercontent.com/86251631/142105004-f6c7607f-8a1d-44b7-9b19-23c98d3e1370.png)

**Comment by Yezi-cmd** [comment]
it need python3.7.1+，I upgrade python to 3.8.3 ，now it is ok！
