### ISSUE TITLE
[BUG]:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hub.towhee.io', port=443): 

### ISSUE THREAD

**Issue by Yezi-cmd** [milvus-io/bootcamp#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use reverse_image_search and deploy with Docker Compose，the container  ‘img-search-webserver’  always restart。And docker logs Id show：
      requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hub.towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image_embedding_resnet50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcf90521790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Why？？

### Software version

```markdown
Milvus: [2.0.0rc8]
Server: [2.0.0]
Client: [2.0.0]
```

**Comment by jaelgu** [comment]
@Yezi-cmd Can you visit hub.towhee.io ? If not, try with VPN.

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd Can you visit hub.towhee.io ? If not, try with VPN.

I can visit hub.towhee.io.

**Comment by Yezi-cmd** [comment]
> @Yezi-cmd Can you visit hub.towhee.io ? If not, try with VPN.

sorry,My localhost can visit hub.towhee.io,but my servers can not, my  servers can visit Intenet by proxy.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
