### ISSUE TITLE
[BUG]: Deploy with Docker Compose, img-search-server is always restart?

### ISSUE THREAD

**Issue by Yezi-cmd** [milvus-io/bootcamp#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy with Docker Compose, img-search-server is always restart.
docker logs img-search-webserver show :
     raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hub.towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image_embedding_resnet50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa5ae436610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

### Software version

```markdown
Milvus: [2.0.0rc8]
Server: [2.0.0]
Client: [2.0.0]
```

**Comment by shiyu22** [comment]
Yes, the webserver will [always restart in docker-compose.yaml](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/docker-compose.yaml#L74).

I think it is caused by the network, maybe you need to connect with proxy.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
