### ISSUE TITLE
It is difficult to get data from Baidu net disk

### ISSUE THREAD

**Issue by yamasite** [milvus-io/bootcamp#98]
In lab1_sift1b_1m.md, it is difficult to get data from Baidu net disk in Ubuntu because you have to install a client with a Baidu net disk account. Is there an alternative? How about storing the data in the GitHub repo?

**Comment by JackLCL** [comment]
If you are using Ubuntu18.04, you can easily  install Baidu net disk.  You can reference https://pan.baidu.com/download.
