### ISSUE TITLE
[BUG]:  unhealthy mols-search-webclient:2.0

### ISSUE THREAD

**Issue by rohanvarm** [milvus-io/bootcamp#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the directions to set everything up using docker but am  unable to get the client working, (verified that the server is working, so is the client frontend it's just the connection between the two.

15fafcbbb422   milvusbootcamp/mols-search-webclient:2.0      "/bin/bash -c '/usr/…"   28 minutes ago   Up 28 minutes (unhealthy)   0.0.0.0:8899->80/tcp, :::8899->80/tcp                  molsearch-webclient

Does anyone have any idea? 

### Software version

```markdown
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS                      PORTS                                                  NAMES
1eea86b1a546   milvusbootcamp/mols-search-webserver:2.0      "/bin/sh -c 'python3…"   53 minutes ago   Up 52 minutes               0.0.0.0:5000->5000/tcp, :::5000->5000/tcp              molsearch-webserver
4d838cabb812   milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106   "/tini -- milvus run…"   53 minutes ago   Up 53 minutes               0.0.0.0:19530->19530/tcp, :::19530->19530/tcp          milvus-standalone
15fafcbbb422   milvusbootcamp/mols-search-webclient:2.0      "/bin/bash -c '/usr/…"   53 minutes ago   Up 53 minutes (unhealthy)   0.0.0.0:8899->80/tcp, :::8899->80/tcp                  molsearch-webclient
9a74b7aedabf   quay.io/coreos/etcd:v3.5.0                    "etcd -advertise-cli…"   53 minutes ago   Up 53 minutes               2379-2380/tcp                                          milvus-etcd
35baa2300184   minio/minio:RELEASE.2020-12-03T00-03-10Z      "/usr/bin/docker-ent…"   53 minutes ago   Up 53 minutes (healthy)     9000/tcp                                               milvus-minio
8dd8a719554c   mysql:5.7                                     "docker-entrypoint.s…"   53 minutes ago   Up 53 minutes               0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   molsearch-mysql
```

**Comment by shiyu22** [comment]
I think that you need to modify the port on [line 93](https://github.com/milvus-io/bootcamp/blob/master/solutions/molecular_similarity_search/quick_deploy/molsearch-docker-compose.yaml#L93) to `8899`.

**Comment by rohanvarm** [comment]
I did that, still doesn't work. Is it because I need to do something with the app network
      app_net:
	ipv4_address: 172.16.238.13 ?

Thanks!

**Comment by aharonh** [comment]
I can fix this. please assign me this task.

**Comment by shiyu22** [comment]
Thanks @aharonh and it merged :)
