### ISSUE TITLE
[FEATURE]: Suggest that the "paraphrase-mpnet-base-v2" model be replaced with the multilingual version.

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/bootcamp#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I found that both `question_answering_system` and `text_search_engine' projects adopted the `paraphrase-mpnet-base-v2` model for embedding:
[https://github.com/milvus-io/bootcamp/blob/master/solutions/text_search_engine/quick_deploy/server/src/encode.py](url)

I recently tried `text_search_engine` on some Chinese documents [https://github.com/smoothnlp/FinancialDatasets](url). I found that `paraphrase-mpnet-base-v2` performed horribly with the Chinese language.

I then found this `paraphrase-multilingual-mpnet-base-v2` model which is the "Multi-lingual model of paraphrase-mpnet-base-v2, extended to 50+ languages."
[https://www.sbert.net/docs/pretrained_models.html](url)
[https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2](url)

I also tried it in practice. It performs very well with the Chinese language.

Perhaps it is worth update `paraphrase-mpnet-base-v2` model with its multilingual version?

It is not cool that the demo only works with the English language.

**Comment by shiyu22** [comment]
Got it, and thank you for your suggestion :) The model does look popular and huggingface has been implemented, but we have no plans to implement this at the moment. 

By the way, would you like to write another encode.py to contribute to [QA](https://github.com/milvus-io/bootcamp/blob/master/solutions/question_answering_system/quick_deploy/server/src/encode.py) and [text_search](https://github.com/milvus-io/bootcamp/blob/master/solutions/text_search_engine/quick_deploy/server/src/encode.py)? And you can update the README that can use your encode file if anyone wants to use the Chinese dataset.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
