### ISSUE TITLE
[BUG]: Docker Compose Client not returning correct topK results

### ISSUE THREAD

**Issue by michaelteo** [milvus-io/bootcamp#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I change the TopK slider on the img-search-webclient, it does not update the results. it just stays at 10 results. 

### Expected Behavior

When I change the TopK slider on the img-search-webclient, it should update the results to return topK results. 

### Steps To Reproduce

```markdown
Tried to use the latest docker-compose yaml in https://raw.githubusercontent.com/milvus-io/bootcamp/master/solutions/reverse_image_search/quick_deploy/docker-compose.yaml

permalink: https://raw.githubusercontent.com/milvus-io/bootcamp/aa4af772b11658edf8d6058370830e8b6229552f/solutions/reverse_image_search/quick_deploy/docker-compose.yaml

1. I downloaded it via wget ttps://raw.githubusercontent.com/milvus-io/bootcamp/master/solutions/reverse_image_search/quick_deploy/docker-compose.yaml
2. run docker-compose up -d
3. go to localhost:8001 ( img-search-webclient)
4. Slider for TopK is not updating returned results. Only returns 10.
```

### Software version

```markdown
Milvus: [2.0.0rc8] milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
Server: [towhee] milvusbootcamp/img-search-server:towhee
Client: [1.0] milvusbootcamp/img-search-client:1.0
```

### Anything else?

I believe the issue should already be fixed in source code via https://github.com/milvus-io/bootcamp/issues/658

But the image search client image in docker-compose.yml  (milvusbootcamp/img-search-client:1.0)  doesn't seem to be updated yet to have the fix. the image was last update 6 months ago, but the fix was around 2 months ago. 

I believe the fix is to update the docker container to include the fix in https://github.com/milvus-io/bootcamp/issues/658, then update docker-compose.yaml to point to the updated container.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
