### ISSUE TITLE
[BUG]: audio similarity search solution does not persist mysql database on host machine

### ISSUE THREAD

**Issue by aharonh** [milvus-io/bootcamp#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start the provided docker-compose for audio similarity search, the resulting mysql database is created inside the container folder.

### Expected Behavior

I expect that the database will be persisted (as all other state of the audio similarity search solution)  in the **volumes** host folder. 

### Steps To Reproduce

```markdown
start up the audio similarity solution and checkout the folder solutions/audio_similarity_search/quick_deploy/volumes - there is no mysql data along with etcd, milvus and minio.
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc1]
Server: [e.g. 2.0.0]
Client: [e.g. 2.0.0]
```

**Comment by shiyu22** [comment]
Thanks @aharonh and it merged :)

**Comment by aharonh** [comment]
Thanks @shiyu22 , closing.
