### ISSUE TITLE
[FEATURE]: more robust data import for audio files

### ISSUE THREAD

**Issue by aharonh** [milvus-io/bootcamp#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The only audio file format supported is "wav" and all the files need to be placed in single folder. Most sound libraries are in hierarchical folders structures and contain multiple file formats (aif, mp3, flac etc)

### Describe the solution you'd like

Add support for additional file formats and support import of all files under the selected folder at arbitrary sub-directory depth.

**Comment by shiyu22** [comment]
Thanks @aharonh and it merged :)

**Comment by aharonh** [comment]
Thanks @shiyu22 , closing.
